### ISSUE TITLE
oc_rlvextension has been reset.

### ISSUE THREAD

**Issue by MaXX99** [OpenCollarTeam/OpenCollar#1011]
What version of OpenCollar are you using? 
- 8.2.3000

What behavior did you expect?

What behavior did you see instead? 
- Opencollar reloads and seems to work fine afterwards, except for some smallish issues (some scripts not linked to the collar, the link between the DEM Relay and the collar is not working fully etc) 

What steps does someone need to take to reproduce the problem?
- at firestorm startup
- when adding trustees/owners

**Comment by MaXX99** [comment]
When rebooting the collar I get this in the Nearby Chat window:|

Rebooting your collar...
Found 0 themes
Startup in progress... be patient
RLV active!
Collar ready. Startup complete
oc_rlvextension has been reset. If the script stack heaped, please file a bug report on our github.
Startup in progress... be patient

And in the Script Warning/Error/Debug Window:

[23:10] **RE** Hades Cross Necklace R2 RLV v6.0 - Female [script:oc_rlvextension] Script run-time error
[23:10] Stack-Heap Collision
[23:59] **RE** Hades Cross Necklace R2 RLV v6.0 - Female [script:oc_rlvextension] Script run-time error
[23:59] Stack-Heap Collision

**Comment by Medea-Destiny** [comment]
@MaXX99 how many owners and trusted do you have added to the collar?

**Comment by Pingout** [comment]
The DEM Relay plugin is a Third Party Creator. It's possible the memory error is originating in their plugin. Have you contected the DEM creator?

From https://opencollar.cc/Open-Collar-Designers
Dark Elf Manufacture (DEM) (chloe1928.constantine)
DEM Relay plugin for OpenCollar 40L
Inworld Shop: [http://maps.secondlife.com/secondlife/Adult Hub BDSM/182/157/28](http://maps.secondlife.com/secondlife/Adult%20Hub%20BDSM/182/157/28)
Marketplace: https://marketplace.secondlife.com/p/DEM-Plugin-for-OC-Boxed/21924118

**Comment by MaXX99** [comment]
> @MaXX99 how many owners and trusted do you have added to the collar?

Mmmmh is there a limit :) I might have quite a few but I guess I will reset all of my collar and start fresh

> The DEM Relay plugin is a Third Party Creator. It's possible the memory error is originating in their plugin. Have you contected the DEM creator?

Never had issues with it before, the problem popped up a few weeks ago and never went away ... As I said I will be restarting from fresh

**Comment by Medea-Destiny** [comment]
@MaXX99 > Mmmmh is there a limit :) I might have quite a few but I guess I will reset all of my collar and start fresh

There isn't officially a limit, but their keys all get stored in script memory and LL are absurdly stingy with how much script memory they give us. The oc_rlvextension script has to cycle through all owners and trusted and apply exceptions to them, so generally if it runs out of memory (that's what the stack-heap collision is) it's because there are more people added to the combined owners + trusted lists than the script has room for. 

In OC9 we will move to a different way to store owner/trusted lists which will mean you'll be able to add crazy amounts, but for now please try removing a few people's access and report back if that clears up the issue for you. Thanks!

**Comment by SilkieSabra** [comment]
I'm closing this on the assumption that the memory issue will be addressed in a future update.
