### ISSUE TITLE
Problem with collar show / hide in scropts

### ISSUE THREAD

**Issue by JoyAcker** [OpenCollarTeam/OpenCollar#1052]
OC v 8.2.3000.  Collar is *RE* Raven

Collar show or hide issued in a script "detach" event is heard by the collar but the collar does not show or hide.
It works fine if the show or hide command is issued elsewhere in a script (eg on attach) or manually in chat.

Detail:
The situation is bit involved, but here are the key facts
- collar is *RE* Raven
- /1 xx show   and  hide commands work fine in local chat
- issuing those commands in a normal script both work fine
- issuing either show or hide in an attach event works fine
- they both fail when used in a "detach" event, even though a "snooper script" in the collar confirms the command is being heard by the collar.

Context
The use case is for outfits, to show or hide the collar without manual intervention.  (This is for the receiver part of a remote hud where the owner may be in a different sim from the wearer)

So, plan "A" which works (technically)  is to have two little huds, one to show the collar one to hide it; which can be part of the outfit.  On attach they issue the command then detach.  This is awkward to organise though as the "hide" hud has to be attached when the outfit it being taken off!

Plan "B" is a single HUD that will show the collar on attach and hide on detach.  

I have verified that the hide command is being executed - trace spam befoe and after the hide statement all show up in chat; and a snooper script in the collar is hearing the hide command.

So I have two questions:
- what is going on and how can I fix it
- is there a better way to AUTOMATICALLY show or hide collar as part of wearing outfits.  Oh, the collar is in #RLV/.outfits/.core

**Comment by Pingout** [comment]
@Medea-Destiny I seem to remember you suggesting that the oc_themes script will need to be revised for Version 9.x collar? I believe you wanted to remove the Show/Hide section from oc_themes, placing that code into another script. Would this issue be addressed at this future revision?

**Comment by JoyAcker** [comment]
Further to my original issue, when i checked the version of the collar in .core is not actually the current version!

**Comment by Medea-Destiny** [comment]
This will be the collar failing to auth the object, because it's detached and therefore no longer possible to identify the object's owner.  When you want one script to react to chat from another script that's issued in that script's detach event, you need to not rely on detecting object owner. That means the command would be spoofable by anyone, unless it's using a secret channel or exchanging secret credentials in some form, which obviously we can't do in an open source script.

We could consider adding a channel for trusted communication (for example always accepting a command sent prefixed with (prefix)(password) as having owner permission, but only doing this if such a password has been explicitly  provided by the wearer. 

In the short term @JoyAcker I suggest you drop a small additional script in the collar that listens on a secret channel, and relays what it hears by link message. Something along the lines:
``if (channel==SECRET_CHANNEL && llGetSubString(msg,0,1)=="jo") llMessageLinked(LINK_THIS,0, llStringTrim(llGetSubString(msg,2,-1),STRING_TRIM),llGetOwner());``

...which when it heard "jo mycommand" on the secret channel, would send "mycommand" to be processed by the collar as if the wearer had issued the chat command.

**Comment by JoyAcker** [comment]
@Medea-Destiny - thanks for the suggestion.  I wasn't aware one could do that.  I notice you use LINK_THIS not LINK_SET, so to be clear that little relay script goes in the collar root prim?

**Comment by Medea-Destiny** [comment]
@JoyAcker Correct. You could use LINK_SET and put it somewhere else if you wanted, but as standard we're only targeting scripts in a single link in OC, so LINK_THIS will generally do the job!
