### ISSUE TITLE
an idea

### ISSUE THREAD

**Issue by silentwar-resident** [OpenCollarTeam/OpenCollar#1060]
I would like to suggest that we code up  lovesese  toys like vibrators as part of open collar if they consent to it...

**Comment by SilkieSabra** [comment]
what are lovesese toys?  anyone can turn a modifiable scripted object into an Addon using the Addon template provided here:  https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/spares/oc_addon_template.lsl

**Comment by silentwar-resident** [comment]
Its like a rl toy can be  controlled in sl Or through app  there is also even a avsitter plug in can do it. I can ask my friend to give a demo how it works . She scripted her own remote in sl.but  don't know how to get it into open collar.Sent from my iPhoneOn Jul 19, 2024, at 1:16 PM, Silkie Sabra ***@***.***> wrote:﻿
what are lovesese toys?  anyone can turn a modifiable scripted object into an Addon using the Addon template provided here:  https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/spares/oc_addon_template.lsl

**Comment by silentwar-resident** [comment]
Loveesese toys are like vibators for example dilios, ass plugs, etc 

Sent from my iPhone

**Comment by Medea-Destiny** [comment]
We have the capability for interfacing OC with lovense as a plugin or add-on.  If someone would like to develop that they can go ahead -- that's why we're Open Source! If someone wants to contribute that code to the repository we'd be happy to take a look. 

However, it may be that the script would have to have an API token from Lovense to do this, and that probably couldn't be added to an open source script. This might be a situation where the best option is for one of the people who already makes Lovense interfaces for SL to make an OC plugin that communicates with it. The plugin template would be a good place to start and of course we'd be happy to help.
