### ISSUE TITLE
Allow owner to disable hide

### ISSUE THREAD

**Issue by masterofsorts** [OpenCollarTeam/OpenCollar#110]
Can we provide a method where by the owner can prevent the use of <prefix>hide by the wearer?

**Comment by IsabeauConnaught** [comment]
personally i do not support this...in past i have run into situation and places where and when wearing collar was not encouraged, not desired, or it was prohibited. my collar was unlocked back then and ive been given permission to take it off....but not everyone is given such option.

some "hides" their collars by editing its size and position to place them inside their bodies, but others are primarly or exclusively using viewers they just cant do (lumiya, radegast....) and if you change your avatar, you can end with collar in weird location, like hovering half of meter above you.

just my two cents

**Comment by Davros-and-Babble** [comment]
I have to agree to an extent. Since the collars have to be mod for updates, I dont see how you can keep the wearer from hiding their collar regardless with very little effort (edit it transparent, or resize it to where its inside the neck, etc.).  Though I suppose there could be a case where the user doesn't even know how to resize.  Just a thought.

**Comment by zontreck** [comment]
This is being addressed in PR #339

**Comment by zontreck** [comment]
Validating Implementation

**Comment by zontreck** [comment]
Not implemented. Adding now
