### ISSUE TITLE
Leash script can cause small collar wearers to fly to owner and not walk

### ISSUE THREAD

**Issue by NorthGlenwalker** [OpenCollarTeam/OpenCollar#113]
What version of OpenCollar are you using?
Effects all versions of Code in all Grids

What behavior did you expect?
When Collar wearer is further away then the leash length they are pulled and walk (or run) towards the leash holder until within leash length.

What behavior did you see instead?
Small collar wearers can "fly" towards the leash holder and not walk

What steps does someone need to take to reproduce the problem?
Collar worn by a smaller avi, (Dinkie, Faerie etc), leash them and then move further away then the leash length.
In the "not_at_target()" section of code in the leash script it uses "llMoveToTarget(g_vPos,1.0);" where g_vPos is the av center of the leasher, so the z function can be high enough for the collar wearer to "take off and fly"
Fix, get collar wearer's position and use the .z as a reference in the llMoveToTargert
remove -
if (g_vPos != ZERO_VECTOR) llMoveToTarget(g_vPos,1.0);

replaced with
if (g_vPos != ZERO_VECTOR){
     vector currentPos = llGetPos();
     g_vPos = <g_vPos.x, g_vPos.y, currentPos.z>;
     llMoveToTarget(g_vPos,1.0);
}

**Comment by nirea** [comment]
Sounds right to me.  Can you send a pull request?

**Comment by NorthGlenwalker** [comment]
A further sub thought on this which might over rule the pull request. 
At the moment when you fly with a sub "in toe" you pull them along with you, with this patch they would remain on the ground, or at the flying height they are at and only move to the required x/y coordinates causing collar wearers to get jammed in buildings etc. But I guess they do now anyway, an t should come under collar wearer care & safety.

**Comment by Medea-Destiny** [comment]
As North points out, this will fail on stairs. 

Rather than using the wearer's current z, we should use an offset from leash holder's current z representing the difference in hip position when the two avatars are on the same floor. I'd be wary of assuming that the leasher and leashee are on the same floor at leashing time. Without being able to derive avatar foot->hip height (a massive oversight on LL's part -- if we had this we would be able to have furniture that automatically adjusted for avatar height, for example) I'd suggest the best option would be to create a z-offset bodge factor based on llGetAgentSize, perhaps something like:
`vector tv=(llGetAgentSize(g_kOwner)-llGetAgentSize(g_kLeashedTo))/2;
g_fLeashZOffs=tv.z;`

**Comment by zontreck** [comment]
I fixed this in my pull request that also fixes various other leash issues
