### ISSUE TITLE
Feature request - move couples animations over to AO

### ISSUE THREAD

**Issue by NorthGlenwalker** [OpenCollarTeam/OpenCollar#120]
After a particular problem on the Inworldz grid between interaction of leash and couples scripts it got me wondering if the collar is the best place for couples animations.
These animations are available to everyone, where they should in my view be a wearer only available menu, as it is not great RP to force your sub to "hug" or "lick boot" you. By placing them in the AO they are available to the sub, that, if they wish to, they may show their owner their gratitude by using them.

**Comment by nirea** [comment]
I agree with your point about RP, but I'm not sure an AO is a better place for them.  People who want to keep using the couples animations would have to switch to our AO if they're not already using it.  And the AO is normally driven by your inworld animation state, not chat commands.

If we just wanted to solve the RP issue, we could make them triggerable by the wearer only, even if they stay in the collar.

I'm interested in others' opinions.

**Comment by Davros-and-Babble** [comment]
I think there has been a lot of debate between forcing a sub to do something, rather than have them do it themselves, and I think this might fall into that category of debate.   We could allow the wearer to do their own kneeling when told.  But on the same token, we could allow the wearer to sit themselves when told, or put on an item when told, or do other things when told.  If we put the RP back into all of it, the collar would be nothing but a cosmetic piece with very few functions such as the leash.  I do agree that people should do it how it is fun for them though.  If someone wants to RP it rather than have an automated way, then they should do it they way they like for sure,  I'd personally like to have the automations including animating.

**Comment by SharieCriss** [comment]
I would advise against moving couples into the Sub AO for a number of reasons.

- Many use a third party AO that is much more advanced, has dances, etc and don't use the sub AO at all.
- What Davros-and-Babble said (Agree 100%)
- This was done ages and ages ago with the Crawl animations with the result being terrible usability and nobody using it (which relates to my first point.) When OpenCollar came out, the dominate commercial collars had crawl built-in to the collar resulting in a pretty frequently used feature. As OpenCollar has all-but killed off the market for these commercial collars, the result is that you almost never see that behavior anymore. (for reference, I contributed code to add it about 9 years ago which was rejected flat out due to the capability existing in the sub AO.)
- Many people don't use a HUD AO at all and use the build-in Firestorm AO to reduce attachment points / scripts.
