### ISSUE TITLE
Request for Comments: Attachment integration proposal

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#128]
Over at #51 we had a discussion about a "bridge" interface that would allow non collar devices to plug into the collar.  I started listing some features that such an interface ought to have, but would like to take a slightly different direction.

I think the key to making this work is to keep the interface as small and simple as possible.  The one thing that the collar *must* be able to share with other attachments is the access settings (whether someone is owner/trusted/in-group/blocked.  So I want to build a bridge that will support that, and leave everything else (leash points, locking things, etc.) up to implementation inside the attachment.

Here's the proposal:
1. Have the collar listen for attachments registering themselves.  An attachment registering itself will whisper a message on a private channel.  The message will include the name of the menu button for that attachment, as well as a prefix for chat commands that will be sent to that attachment.
2. When it hears a registration, the collar will record the attachment's UUID in an internal list, along with its associated prefix and menu button.  Multiple attachments will be able to register the same button/prefix (each cuff in a set, for example).
3. When a collar user clicks the attachment's button in the menu, the collar will pass that along to the attachment(s) with a llRegionSayTo message.  The message will include the user's name, key, access level, and the text of the button clicked.
4. Similarly, if the collar hears a chat command that uses the attachment's prefix, it will be passed along the same way, with the same information.
5. On rez, the collar will clear its list of attachment registrations.  (UUIDs are regenerated by SL whenever an object is rezzed, so if you've logged out and back in, all attachments need to re-register.)
6. When a user presses the "Fix" button in the menu to have internal plugins re-register themselves, the collar will also broadcast a re-registration request on a fixed private channel, so plugins can respond with a registration message.

Questions:
1. Is there any essential functionality that attachments need, that would be impossible with this interface?
2. How different is this from how cuff/attachment integration has been done in the past?

**Comment by Medea-Destiny** [comment]
A few suggestions, some a little obvious but hopefully useful for clarification:

1. Only allow bridging with an item that is currently attached to the collar wearer.
2. As well as clearing bridged attachments on rez, the collar should also send out a ping telling attachments to re-request registration if necessary. People will get confused if they are supposed to attach things in a particular order. 
3. Auth reporting: bridged attachment can simply request a reply with the auth level of a user key. However this has been (I'm honestly not sure if it still is) possible via the hud channel for any arbitrary item that has can auth, and I'd suggest that this is too useful an option to ignore. Thus I suggest that auth reporting should be separate from the registration process, though there's no reason why registered items and other items shouldn't be sharing a hud channel.
4. Menu requesting: Bridged attachments can trigger a collar menu directly. This will allow items to "inherit" an OC menu in their own menu.
5. Lock state sharing. While I agree leave this to the individual object, it would be nice to have lock state reported to the registered attachment, so that optionally it can inherit the OCs own lock.
6. I think there's a lot of scope in bridging things like leash points, but this is perhaps a secondary consideration that can be added on later.  OC depends on a number of links for things like leash point, floating text prim, as well as the animator etc. links. If registered attachments could register themselves as these links, or at least some of them, it would open up a lot of possibilities. 
On a basic level, being able to adopt the leash point and floating text prim, alongside 4 above, opens the possibility of having a single drop-in script for attachments that allow them to inherit and effectively "become" the collar. This would be very useful for people who like to have multiple collars, as it would allow a hidden (hud?) collar core, with any number of collar attachments that become the physical collar when worn, without having to worry about sharing settings over multiple collars, having to update multiple collars, collisions when multiple collars are worn, etc. It could also potentially allow for things like letting different bridged attachments replace (or add to?) the animation set included in the collar.

**Comment by NorthGlenwalker** [comment]
From a Cuffs linking prospective-
The cuffs have always provided it's own Auth system as it was always considered that the cuffs can work independent to the collar. I have always tried to have the collar-cuffs sync script listen out for changes and forward them on to the cuffs. Since the scripts splitting into separate prims and the linkmessages being sent to to the actual prim this has been a lot more difficult and has required me to kick off a settings restore for the auths so I can pick up any changes. Settings store messages are sent directly to the settings store prim/script so you can not not hear what is being sent to it but by listening to other menu messages you know things like owner lists have changed and then kick off a settings restore, this is of course very wasteful, but at the time I had no input on what messages should be available.
Textures, lock, RLV status, color etc can normally be listened for as those commands are sent to all prims.

First real question is, do we still want the cuffs to remain as a stand alone system, or as a sub system of the collar? All the cuffs chaining/movement-restrictions-when-chained scripts will drop straight into a collar's Apps menu. 
I have currently got the cuffs working as single active script slave cuffs (down from active 5 each).
The Right Wrist (controller) cuff just needs a small section fixing to add new owners then they are ready to go. To go with dumb cuffs the right wrist cuff would need a special rework interface, but this could, I think be made to work on 2 scripts with the other chain control scripts being moved to the collar as option add-ons say with a cuff installer updater for the collar..
