### ISSUE TITLE
Enchancement: Ask mode for public

### ISSUE THREAD

**Issue by SharieCriss** [OpenCollarTeam/OpenCollar#166]
Currently when public mode is used and someone uses it to harass / grief, you have to get within 10m or so of the abuser, add them to the blacklist, and they can STILL cause problems as the blacklist does not take effect when they have open menus resulting in a need to unlock, remove the collar, add the collar, relock, etc. especially as the abuser can continue to use the menus even after you've TPed away.

While solving that particular issue would be nice, a much more simplistic solution would be to have an Ask mode available where you can have public on, but receive an approval dialog indicating that "Someone Resident wants to interact with your collar. Allow? [Yes] [No]"

Instead of Public mode being a toggle on or off, make it more like the relay: Off, Ask, Auto

**Comment by mailani19** [comment]
I think the main point of it being public is exactly so that people can grab you without needing to ask,
Having people add an auth based check or a confirm dialog check is going to add a good bit of code to the script without really any benefit.  I suggest if you don't want just anyone being able to grab your collar that you add them to your white list (confirm dialog).  it seems the ability to do what you want is already there.

**Comment by SharieCriss** [comment]
No, You completely miss the point of public mode. The point of public mode is so that you don't need to whitelist individuals. If you TP into a playground, you are not going to get within 10M of everyone that you MAY like to play with and add them to the whitelist, and then have to clear the whitelist when it fills in 2 minutes. That would be silly. I've already explained why blacklists won't work either (and again, you can't put many names in there.)

Think of it more like the RLV relay. What would you do if there were no ask mode. Whitelist every bit of furniture you MAY want to play with? Toggle it on and off only when nearby people are those that you want to play with? 

We are talking about perhaps 15 lines of code that would be a large benefit. I completely reject your premise that it would be of no benefit.

**Comment by zontreck** [comment]
Reading the original post- I agree with you that there should be an -option- when enabling public mode to have it be auto, ask or Altogether, off. This is something i could look into writing? And it would be perhaps more than 15 lines of code though to accomplish this task but i'd be up to it.

**Comment by tamakohan** [comment]
IMO there's no need for an Ask mode here.

Just turn off public, let people ASK you (i.e. talk to you) if you are interested in playing with them, then if you are, add them to Trusted. That's what it's there for.

Alternatively, if you want curious collar clickers to know you're interested without so much as having to speak, again turn off public, but also turn on capture mode and keep risky off, then when people touch your collar it will ASK you if you want to allow them to capture you. You can either accept the request, or you can reject it then add them to Trusted and play that way. Perhaps a useful addition would be to add "Add to Trusted" as an third option on the currently yes/no prompt for whether you want someone to be able to capture you.

I doubt this could be implemented as requested without wide reaching implications and definitely not in 15 lines of code; you're talking about adding a whole additional userlist similar to Trusted but treated as group, to which people would need to be added when you accepted their ask, people clicking would need to be notified when you've been prompted/accepted/rejected, you would need to be able to see who was on the list and clear it or remove individual entries, entries would need to expire automatically in some fashion... That's just off the top of my head.

**Comment by zontreck** [comment]
@tamakohan Please don't criticize my estimations. Thats all they are estimates. And yes it could be accomplished by just changing a few lines under the auth script.  And if i do implement this, it would be as a option to have this behavior on public access, it would not be default, and would not be forced on anyone. More than likely i'd make it by chat command so the menus don't need to be more complicated. Though i am still deciding on this.

**Comment by marrmist** [comment]
I see the value of this idea and I disagree with the assertion that the existing features already cover this use case.  But I do agree that "ask mode for public mode" is probably not the simplest way to achieve the goal.  I would instead consider a setting for "allow strangers to request trusted access" which generates a prompt that allows the wearer to add a person to their trusted list.

I disagree that "entries would need to expire automatically in some fashion."  I think it's okay for the wearer or their owner(s) to tidy the trusted list just like they normally would.

**Comment by mistressohm** [comment]
The only issue with the Trust list not getting auto-cleaned is that there's only a certain amount of UUID's that the collar can effectively hold between Owner, Trusted, and Blocked.  At some point, the list of UUID's held in memory is going to overwhelm the scripting if the entries no longer needed aren't purged.    

BUT, there is an alternative for per-playground access.  Most locales have a group set up, which means you can activate that group and then toggle "Group" access.  This prevents you from changing your active Group, and allows everyone in that group to interact with your collar.  When you're done playing, untoggle Group access, then set a different group. 

This means that everyone you run into needs to be in that same group as you are, but, this is pretty common, and often required in roleplay sims, so that the RP managers can keep their population informed and deal with troublemakers.  No reason why this can't be leveraged as a semi-Public yet still secure option.

**Comment by zontreck** [comment]
Public ask mode would likely use either one or two uuids in a list, nothing more than that, when someone else is granted it'd rotate out the old memory.  so it would not be a humongous list that never gets emptied :)

**Comment by marrmist** [comment]
That makes sense zontreck.  I would still suggest more than just a couple, because the point of public mode is for multiple people to be able to control the collar at once (otherwise you'd use capture mode).

Also one big problem with group mode is that most places are not strict about members setting their active group to the sim group, so most people don't do so, and the script can't detect if they're in a group if it isn't their active group.

**Comment by zontreck** [comment]
I've honestly never seen a situation (at least in recent memory), where more than one person was trying to use the collar menu (and was a public user)

**Comment by zontreck** [comment]
In that scenario i'd agree, group access makes more sense. But with it being suggested to have an ask mode, i'd say like 2 or 3 UUIDs, maximum, and it should clear it after 30 minutes or so.

**Comment by marrmist** [comment]
Personally I agree, but that's also why I always use capture mode instead of public access mode.  So I am trying to get in the mindset of what public mode is for...  I can only imagine it's for group situations where you expect different people to casually push your buttons.  I do agree that 3 is probably enough for almost any situation.
