### ISSUE TITLE
Create Relay HUD as a plugin that can be opened from the collar menu but is not part of the collar object

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#188]
It seems that there are conflicts that can be created just by having a relay embedded in the same object that also uses other rlv restrictions, such as the collar.

In addition, having the relay in the collar creates some user confusion since many collar wearers and operators are not aware that the relay is not affected by collar access settings, nor what it is used for.

The benefit of having a relay in the collar, other than force of habit, is that it allows collar owners to operate the Relay settings.

We could do this with a plugin architecture that allowed the Relay to be separately worn as an HUD and access to the HUD menu from the collar for collar owners only.

Toy Wylie has graciously agreed to let us build this with her Turbo Relay which is public domain in any case, but it's always nice to ask.

**Comment by Drakonadrgora** [comment]
Though I can understand why some may think it's not good to have the relay in the collar I have to disagree. There are some things on the mp that can block touching the relay and not all relays have a chat command safeword or a chat safeword that can be triggered by ((ooc)).

Where the collar global safeword can be. Providing a level of safety that would otherwise not be there. Which would force someone to have to log out of rlv to free themselves under those situations. Which would then cause the collar to send the notice and possibly create unneeded drama at that point.

Yes using the collar safeword still will send out the notice but that is easier to explain and deal with then having to deal with someone possibly having a fit because you logged in with rlv off.

If this process is went through with, you would need to still provide collars with the relay in them for those who don't like the idea of having to wear a relay separately.

Meaning there would have to be two flavors of the collar developed. One for those with out the relay, one for those with the relay. Unless it was made simple enough to either add or remove the relay from the collar at the preference of the wearer. Or the relay in question would have to be made sure it has touch/chat/((ooc)) safeword capability. Which I personally don't know if that relay does. In order for the wearer to be safe from certain items on the mp.

It's not just about the owners, it's also about helping to make sure the wearer remains safe or at least has choices other than logging out of rlv or being stuck until their owner is online and could come help them. Which could cause some wearing a collar to decide it is not worth it.

**Comment by SilkieSabra** [comment]
you could just leave the collar relay script in spare parts and send the HUD relay with the collar, and make sure the relay we send does use a chat command.
