### ISSUE TITLE
Future feature proposal: Access Control List

### ISSUE THREAD

**Issue by tenshilove** [OpenCollarTeam/OpenCollar#190]
I would like to propose an access control list as a next version feature. The proposal comes from testing the Ruby collar scripts, and the amount of granularity offered is impressive and very flexible. It allows to determine what can each level of trust do, and it can be modified by the wearer (if unowned) or by the primary owner (when there is an owner assigned) and i believe it would make the OpenCollar scripts much more flexible.

**Comment by zontreck** [comment]
Can you please define Access Control List, because from my initial glance at the title, i wanted to reply as: We have that, it's called Trusted, Owner, OwnSelf, and blocked.  However after reading what you wrote.. It sounded as if you meant not a ACL, but rather something more of a Access Control Policy system and a editor for those policies.  Now i'll be honest... we would run into a great deal of problems by trying to implement something like this. Our code base is not designed presently to accomodate such a feature. And here is why.. Each script knows what each auth level does, and has it's own parameters for whether that level can do something. To implement something like this... all of us at OpenCollar would have to get together and think of a way to do so, it isn't a one person job.

**Comment by tenshilove** [comment]
Yes, I am sorry I was not terribly clear, I am sorry. It’s correct, my proposal could be construed as access level policies; I agree that it is something more granular than what we have now, but it is something I feel would give a greater deal of control. It’d be great to be able to have, say, primary owner always controlling all aspects of course, but also have the ability to determine which subsystems are available to trusted and to public, i. e., the primary owner can decide that public owners only get access to leahsing and positioning, and that secondary owners get access only to leashing, positioning, rlv and posing. Of course such policies should include the wearer and the wearer and the primary owner, but I digress. I am aware this idea is a major undertaking, I confess my ignorance in the matter but if I can help with ideas and / or insights, I’m your girl. 😊



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jwenting** [comment]
While great to have no doubt it would require pretty much a complete rewrite of many parts of the code.
Each method almost would have to check with the policy agent whether it would be allowed to be executed by whichever avatar (or in case of the relay the triggering device) is allowed to actually execute that piece of code.

I've had to implement such things in enterprise level applications, and even starting from scratch it's a major hassle.
Retrofitting it into an old system is a massive nightmare.

**Comment by tenshilove** [comment]
Oh I definitely wouldn’t suggest that this feature be retrofitted; I was hoping that, say, for OC 8, this could be included as a feature. I know of Doms (me included) who would just love to allow others to manipulate their subs, but do not like to give trusted status unless it’s effectively someone they can actually trust, but feel that the collar’s public mode is a bit, well, too open. A policy agent would allow a granular control over what can be done to the said sub, especially if he/she is into public use. I am also aware that this could potentially be seen as something too paranoid for play in SL, but then again, I’m aware that this idea implies reviewing the code extensively, let’s call it more a “I wish this could make it into OC at some point” idea rather than an “I need this yesterday or else the world is gonna come crashing down on all of us” need. We all have our lives to live, after all, right? 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by zontreck** [comment]
Unsure if your idea is similar or not to the 7.4 Beta : Restrictions Set Access. If it was what you're requesting let me know because that had to be removed for now due to memory issues. This can be accomplished again via a plugin virtually with just copy/paste the old functions from the betas.

**Comment by zontreck** [comment]
I'm going to look at how we can maybe add this into OC 8 by use of the OC API that is being introduced. However each plugin would need to check in with the policy, unless this is implemented at the Dialog level, and we would need to cache the paths in that case. Please let me know your thoughts. oc_dialog is already on my todo list as it has a LOT of stuff in it that could probably be removed as deprecated since only a few functions get used now, NOTIFY, DIALOG, DIALOG_RESPONSE, NOTIFY_OWNERS, etc. 

Most of those functions are internal by the link message system, none of which use fragments of code i found in oc_dialog - remotedialog.

**Comment by zontreck** [comment]
This was attempted in early versions of 8.0 but the lack of reasonable amounts script memory makes this a impossible feature without getting too script heavy. I would like to think that 8.0 is a huge step forward in customizability though, as seen in folders and in outfits there is now a ACL as there was the script memory to do so.
