### ISSUE TITLE
Access Issues using the scripted cuffs set 7.030

### ISSUE THREAD

**Issue by rocketroo** [OpenCollarTeam/OpenCollar#191]
What version of OpenCollar are you using?
OC 7.1 collar, Cuffs set 7.030
What behavior did you expect?
For persons on Trusted list to have access.
What behavior did you see instead?
They were denied access, even with them on Trusted List and I was on Public Access.
What steps does someone need to take to reproduce the problem?
Be Owned and also Self-Owned. Have Collar on and locked, Cuffs on and Locked. Set for Public Access. Adopt a pose from the cuff menu. Add someone to Trusted Menu. Have someone RLV lock you down. Then have person on Trusted menu attempt to access. Unlock self, and again have Trusted person attempt to access. In both cases, I had Trusted Person denied access.

**Comment by zontreck** [comment]
Hey. So auth would not really look at someone's RLV restrictions and determine whether to allow or deny access..  This should be looked into though

**Comment by NorthGlenwalker** [comment]
I assume you tried to set access on the cuffs and see it in the collar, Sorry this has not been possible since 3.741 when we had a Database to link them.
All I can do is have access levels feed down from the collar. The main issue is looping around of any changes made on one device feeding into a continuous loop.
So, think of the collar is the master device, any setting set there will feed down onto the cuffs but not visa versa.
But the cuffs will work independently of the collar if required

**Comment by zontreck** [comment]
North? If you allow modification of the auth list in the cuffs, it should still work as expected. We don't know if the person is added to trusted on cuffs or on the collar. But either way, i have heard issues where the collar settings do not get passed to the cuffs.
