### ISSUE TITLE
Feature Request: Secure RLV restrictions

### ISSUE THREAD

**Issue by Neceh** [OpenCollarTeam/OpenCollar#202]
I'm looking for a option that adds a exception on RLV settings like @TPloc and @TPlm and perhaps more.
Currently i cannot block these RLV settings on or off. And the problem is with another item adding these settings unwanted.

**Comment by zontreck** [comment]
So here's what the Secure RLV does: If you have a secure restriction blocking that feature then another product cannot come along and add an exception unless that exception already existed, though i could be mistaken. the _sec restrictions also work another way, when you have a secure exception, another product cannot override it. 

Now i don't think you can completely prevent another product from setting a restriction. This might be something you could bring up to Marine Kelley though as she pretty much maintains RLV, and if something like that were to become a thing in RLV, i can pretty much assume that RLVa will adopt the same way of doing it.

Unless @nirea, or @Medea-Destiny  know of ways to accomplish this... I really don't think there's much we can do on our end.

**Comment by Medea-Destiny** [comment]
As Zontreck says, via scripted RLV commands it is only possible to stop other items adding an exception to a restriction you've set, not stop them adding restrictions. RLV, but not RLVa, actually does support command blacklisting. Most people use RLVa (Firestorm) though. We'd have to convince Kitty Barnett rather than Marine Kelley. 

We could potentially offer blacklisting in the collar for commands the collar process either via menu/chat commands from the collar itself or via the relay, but we can't control what other attachments do.
