### ISSUE TITLE
Feature proposal: Moving content back to main prim

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#210]
This is purely to make it easier on the community with putting the global / default settings card into the collar. Another possible idea is to simply move the oc_settings script back to the root prim as with settings there is no performance gain.

**Comment by Judge17** [comment]
Agreed; oc_settings and .settings both in root. Could leave most scripts unchanged. They interrogate oc_settings at startup, it responds with its link number, thereafter scripts direct messages to that link number. Good idea.

**Comment by zontreck** [comment]
Another possibility is moving oc_rlvsys, oc_dialog, oc_settings, oc_auth, all back to the root prim. While keeping anims and such separate to reduce lag on sim/ and client.

**Comment by tamakohan** [comment]
Just wanted to share some potential concerns:

- oc_dialog
  - As far as I understand this _has_ to be a child prim. It renames itself (`llSetObjectName`) before speaking / showing menus, so if this script were in the root prim then this might have unforeseen consequences.
- oc_rlvsys
  - RLV commands in the viewer are scoped separately per child prim. So, with this script in a child prim, if some other script (perhaps unrelated to OpenCollar, or a plugin) in the root prim sets some RLV restrictions directly, they'll be processed separately and won't interfere with each other. If this script is moved to root then an unrelated script could mess with restrictions issued by oc_rlvsys or vice versa. So this may still want to be kept in its dedicated child prim too.
- oc_settings
  - Not sure what the original reason was for having this in a child prim, or why it's being moved back now. The only potential reason I see to keep this in a child is to edit the .settings notecard more easily, because it takes ages to load the contents of the root prim (or any prim with a lot of contents).
- oc_auth
  - No idea why this was ever in a child prim in the first place, moving it to root sounds good to me.

**Comment by zontreck** [comment]
To address the concerns with this proposal: 
The scripts can always be modified and will have to be modified in order to move them back. 
Considering that all the scripts reference LINK_DIALOG, LINK_SAVE, etc. All of them will need to have these values updated. And there is also no reason why the dialog cannot set object name, as it won't change the actual object name in inventory.  Therefore the script would just need to set that value on attach specifically, not rez, to avoid it renaming the object.
As for RLV, Yes. The viewer does recognize restrictions based on the actual prim UUID. However, there are plugins that attempt to modify the restrictions, and i'll give you an example: Terminal. If we move the rlvsys back, then a @clear will do exactly what it was intended to do.

Not sure why settings was ever moved, however you are not correct about it making .settings easier to edit by it being in a child prim. Many are not builders and get confused by the prim structure and the concept of editing a linked prim. Moving this back to the root prim will enable people to edit .settings much easier, and to create a .settings if it does not exist as it will require only 3 steps as opposed to perhaps 4 or 5. For those who don't quite understand editing linked prims, it becomes a 10 step process when you have to explain every little step.

**Comment by zontreck** [comment]
Also it may be worth noting that the scripts will be getting moved back to the root prim, other than the anim script. I'm just trying to decide how to handle the update to move the scripts out of the linked prims.
