### ISSUE TITLE
Feature request: read-only 'registry'

### ISSUE THREAD

**Issue by Tuco-Solo** [OpenCollarTeam/OpenCollar#212]
As an OC plugin developer,
I would like to be able to easily retrieve several abilities and settings,
so that I won't have to code different methods to retrieve the information that I need.

For example, the RLV-state can be retrieved by monitoring the RLV_ON/OFF messages. yet, for the collar's locked state there doesn't seem to be a mechanism other than listening for both dialog responses *and* channel commands. And if I want my plugin to ask for all residents on the owners, trusted an blocked lists, the LM_SETTINGS_RESPONSE messages must be monitored.
Last example: my plugin would benefit from knowledge about the maximum number of residents that are kept on those lists before any new addition would silently fail. (If found this to be hard coded 28 somewhere.)

So I wondered whether a generic system could be introduced where both scripts and plugins can tell others about their current state and settings.

**Comment by zontreck** [comment]
Have you tried the git master version of OpenCollar? It has a fix in oc_settings to echo on LM_SETTING_(?) whenever save, or delete is called. It already echos in v7.1 on read so i added in the save and delete echos.

**Comment by zontreck** [comment]
As for what you mean by "abilities", im unsure. You will have to clarify that for me. 
To address the owner count. That much is simple to do. Just parse the string value of the owners, trusted, etc, into a list and then run a llGetListLength on the resulting list and you have the total. OpenCollar does not provide a read-only value indicating lengths of lists. We can mark this down as a feature request... but i am not sure that this is feasible to implement with memory restrictions placed on scripts.

**Comment by zontreck** [comment]
I'll quickly also answer the lock state. Yes it can be obtained. Look in oc_auth to see what the token it saves is and you will be able to listen for that in your script.

**Comment by Tuco-Solo** [comment]
For example:
g_iPeopleCap in oc_auth
There seems to be no way to 'read' this value.

Or g_lTempOwner, also in oc_auth.

**Comment by zontreck** [comment]
I see..  As for the temporary owner, you can look up the temp owner by listening for the SAVE or DELETE calls.  Unfortunately though the save and delete calls will not echo back to other scripts until the next update hits, so im referencing current github behavior.  If we were to add a call to get every single read-only variable in a script though it would use all our script memory available to us. Some things we can certainly look into adding in, however static values that never get changed, you are encouraged to just research what those are set to if you need to know that info in your script.  Aside from having a function to dump every variable into a linked-message and just do a thing where you pull the relevant setting, theres not much we can do to change this specifically.

**Comment by Judge17** [comment]
For my own use, I wrote a repeater script that lives in the settings prim; it inspects all the SETTINGS calls that go to oc_settings, and when it sees a value that's significant to my functions, it repeats the value to my scripts (different message id to prevent looping, of course).

**Comment by zontreck** [comment]
@Medea-Destiny do you think it might be possible to implement something like this? A "registry" of sorts...  Unfortunately the easiest way i can see to accomplish this without the memory problems it might pose would be the experience memory storage, however that is not available grid wide yet.  Of course when that feature does become available the oc_settings script will pretty much become obsolete anyhow since each individual script will then be free to just ask SL for the settings and they'd be returned in a dataserver event.

**Comment by zontreck** [comment]
Actually i should also tag @nirea  - Could use your thoughts on this as well

**Comment by nirea** [comment]
Two thoughts...

1. Didn't we once look into serializing settings into a prims media params?  Maybe that would work.

2. What if instead of a registry, we formalized that pattern that @Judge17 implemented?  A script could send a message to the settings script saying "i'm interested in any changes to setting X".  The settings script could remember those subscriptions and send events as link messages to the prim that subscribed whenever that setting changes.

**Comment by zontreck** [comment]
hmm, i like the Subscribe idea. And yea medea is working on the media param storage. Although now that we got a test version of the latest git scripts out i could probably look into helping her out with getting the media params working as a place to store both settings and misc data.

**Comment by Medea-Destiny** [comment]
I'm currently experimenting with the prim media params option. So long as we have some sensible rules as to how the data is stored, it would be relatively simple for any script to retrieve any setting it wanted. This would also have a significant advantage in terms of script load, as via the linked message system, a lot of scripts will be receiving unnecessary link_message events. This could also make the update process rather smoother. 

One concern is that as these are prim properties we're setting, the reliability of setting them in an attachment is questionable. This may be solved by saving a last updated value to prim properties so the settings script knows whether the media params are in sync.

**Comment by zontreck** [comment]
hmm, well i know with other products that use attachment properties to save their settings, esp inside of linked prims, the SL bug remains that the asset server won't update reliably. This means that even the script settings do not save properly. So we'll need to figure out a way to combat this so that if the attachment properties do not save, that at least the script memory remains intact.

**Comment by Medea-Destiny** [comment]
Hence the 'last updated' flag. Worst case is it may require setting prim media values on rez.

**Comment by zontreck** [comment]
This cannot be implemented as requested because LSL is not object oriented and has no concept of classes or static properties. All tests at producing a read-only registry have simply resulted in too high memory usage, which is not acceptable. I apologize but this request is being closed as won't implement.
