### ISSUE TITLE
capture while public access off

### ISSUE THREAD

**Issue by RayZopf** [OpenCollarTeam/OpenCollar#228]
What version of OpenCollar are you using?
7.2

What behavior did you expect?
when capture is on - esp. with risky, one should be able to actually use the collar to get to the capture menu

What behavior did you see instead?
capture on and risky does post messages to local chat about 'capture me'
when public access is not set, one actually cannot capture - as collar does not respond to clicks and commands, not giving the menu (not even the capture one)

What steps does someone need to take to reproduce the problem?
wear a (fresh) collar
enable capture and set it to risky
have public access not enabled
try to capture

**Comment by Medea-Destiny** [comment]
Fix in #232 , I agree this seems utterly counter-intuitive and makes capture basically redundant!

**Comment by JaynaDover** [comment]
Capture is broken in other ways too and has odd limitations.
First, if public access is on and capture is on, the user will get two popups, the first asking if they want to capture and the second the main collar menu. Clicking on the responses for the capture dialog does nothing as I believe the collar menu "kills" the capture menu listener or something (I'm not sure what's going on behind the scenes.)
Regarding the limitations, the TempOwner can go into the relay settings and enable helpless but not change the relay mode from auto to ask for example. That's - really odd.

Capture doesn't appear to give you much more access than public, but it does lock down the wearer a little more than plain public.... But only a little. The wearer can still go in the RLV menu and disable RLV - again, this makes no sense.

As authentication restrictions are All over the code everywhere, in nearly every script, I'm not sure it makes sense to attempt to fine tune the restrictions on TempOwners. Perhaps a checkbox for the wearer that enables either full owner (with the exception of Access) or public level permissions on TempOwners depending on how risky the wearer is feeling.

**Comment by SharieCriss** [comment]
I've made a number of changes which fixes capture for Public mode, have not yet done fixes for public off but am working on those too. I've also run around the code and fixed a whole bunch of things that needed fixing in order for Capture to work properly with some sense of reason. I don't believe giving Owner permissions makes sense, as in Capture mode you still don't want people messing with your access lists. Along these lines, I added a link message to the dialog script which clears pending dialogs - needed for many situations like adding someone to the Ban list - or ending capture play. If they still had a menu open, they retained the current permission until they no longer use the menus, which really is quite undesirable. So yeah - I've made changes in lots of places because it was needed. I'll probably have to send my diff from 7.3 to Medea or fork it here on Github

**Comment by zontreck** [comment]
@SharieCriss in 7.3 the TEMPOWNER access level was made equal to trusted. And access to lock/unlock and to the Access menu is disallowed.

**Comment by zontreck** [comment]
Additionally while public is off, CMD_NOACCESS represents that. Which is why capture presently does not work when public is off.

**Comment by SharieCriss** [comment]
As a FYI, I did resolve all the outstanding issues I could find with Capture and have it working well with both public and non-public.... I'll get the patch set to Medea so she can do whatever she wants with it :)
I had to add a new link message to Dialog too so there is a way to clear requests. The way it remembers access levels despite the level changing for the user causes problems.

**Comment by zontreck** [comment]
OK @SharieCriss - You can also send the patch to me inworld (Aria (Tashia Redrose))
