### ISSUE TITLE
Updater should only say DONE when it's actually DONE

### ISSUE THREAD

**Issue by tamakohan** [OpenCollarTeam/OpenCollar#284]
What version of OpenCollar are you using?
7.4 beta 2

What behavior did you expect?
When the updater says DONE, I expect to be able to start fiddling around with the collar straight away, for example, renaming it. There should be no more installation messages from the collar or updater, nor should they do any further actions themselves after this point.

What behavior did you see instead?
When the updater said DONE, I renamed the collar, but there were then chat messages from the collar (not the updater) such as "Installation is finishing!", the collar managed to rename itself back during this time so I had to rename it again. (I presume in the same way, had I clicked the collar, I would have had menu buttons missing, like mentioned in the notecard.)

What steps does someone need to take to reproduce the problem?
Update a collar to 7.4 beta 2. My collar was 7.1 before the update, not sure if this matters.

**Comment by zontreck** [comment]
Okay i'm going to be honest here.. This is just a case of impatience. The updater itself had no more tasks. The whole "Installation is finishing" was added because there are infact still tasks taken by the collar to finish installation such as restore settings. There's nothing i can do to change this. Until the collar actually says: Installation Complete. The installation isn't done. This is what led a lot of people to be confused about the RLV button being missing (Although that partially can be blamed on oc_sys.. fixed in beta 3 once released)

**Comment by lillith-xue** [comment]
Maybe a simple solution to this would be instead of the updater saying "done". Let it say something like "rebooting collar". And the collar then says the "done" message after reboot.
