### ISSUE TITLE
Revert to pre-Apache license?

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#29]
There are a few scripts that VD claims are under the Apache license rather than GPL 2.  We should consider reverting to the last version that was pure GPL.  Is it worth it?  List pros and cons here.

**Comment by WendyStarfall** [comment]
Feel free to review the git log where you will find that I have composed these scripts. They have been composed from ground up.

If you swap the Apache 2.0 with the GPL,v2 under the false pretenses to "revert" something, you will be in violation with the terms that I have chosen for my work.

**Comment by nirea** [comment]
I think you misunderstand what I mean by revert.  We would roll back the repo to its state from last June, just before these non-GPL scripts were added.

**Comment by kyrahabattoir** [comment]
Sounds like a great idea.

**Comment by pixelwork** [comment]
from my understanding you can just keep the apache license, nothing in that license prevents you from using the code and releasing it again, you even dont need to release the source when you change things.

what you cant do is changing the license from apache to gpl, that would be a violation

**Comment by TakatSu1** [comment]
I have to agree with pixelwork on this one.  To just change out the license would, it seem to me, to be some sort of violation of IP/Copyright law.  Otherwise someone could just "re-license" anything they wish to a license that they feel is more advantageous to them.

Where it might get interesting is if some file were originally GPL and then was moved to Apache and now we're talking about moving it back to GPL.  That water seems rather muddy and murky to me, and fraught with all sorts of hazards.

**Comment by nirea** [comment]
We've rolled back to 6.5.5, which was pure GPL, and are building on that.  It also avoids the problematic inworld permissions introduced with 6.6.x.

**Comment by TakatSu1** [comment]
Sounds like an equitable solution free of entanglements
