### ISSUE TITLE
Use Github Pages for new website

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#31]
The old opencollar.at domain is not under the control of the official OpenCollar team, so we should set up a new website.  I think using a Jekyll-based Github Pages site would be the simplest option.  If anyone wants to set up a skeleton for that, please send a pull request!

**Comment by WendyStarfall** [comment]
Our team is still the "official" team for the upstream repository that resembles what the device is today, and what thousands of users acquired. They must not be confused or mislead who to trust.

I'm not granting you permission to use any of the text and content on opencollar.at for your own design.

**Comment by nirea** [comment]
Noted your preference about the web content, Wendy.  That's fine.

**Comment by silentwar-resident** [comment]
also, go to https://www.namecheap.com they have a lot of domains on sale for the first year....

**Comment by pixelwork** [comment]
wendy your can call yourself being official team, thats pretty fine since the virtual disgrace version of opencollar is still the most popular version but most of OC is GPL, or under other quite liberate licenses.

I agree with you, you or possibly better virtual disgrace is holding the copyrights for the opencollar.at webside. Any other claiming to own any rights on texts and using them from opencollar.at is a clear violation

But if somebody else comes and uses the GPLd parts, even under some circumstances may use the apache licensed parts and distributes it without claiming that they own contents from opencollar.at then thats perfectly ok.

And if that version becomes more popular then the virtual disgrace version then that version will become the "official" version

**Comment by silentwar-resident** [comment]
H5 to ya pixelwork.
-------- Original message --------From: pixelwork <notifications@github.com> Date: 11/24/17  8:03 AM  (GMT-08:00) To: OpenCollarTeam/OpenCollar <OpenCollar@noreply.github.com> Cc: Silentwar Resident <internetking@internetking.us>, Comment <comment@noreply.github.com> Subject: Re: [OpenCollarTeam/OpenCollar] Use Github Pages for new website (#31) 
wendy your can call yourself being official team, thats pretty fine since the virtual disgrace version of opencollar is still the most popular version but most of OC is GPL, or under other quite liberate licenses.
I agree with you, you or possibly better virtual disgrace is holding the copyrights for the opencollar.at webside. Any other claiming to own any rights on texts and using them from opencollar.at is a clear violation
But if somebody else comes and uses the GPLd parts, even under some circumstances may use the apache licensed parts and distributes it without claiming that they own contents from opencollar.at then thats perfectly ok.
And if that version becomes more popular then the virtual disgrace version then that version will become the "official" version

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenCollarTeam/OpenCollar","title":"OpenCollarTeam/OpenCollar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenCollarTeam/OpenCollar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pixelwork in #31: wendy your can call yourself being official team, thats pretty fine since the virtual disgrace version of opencollar is still the most popular version but most of OC is GPL, or under other quite liberate licenses.\r\n\r\nI agree with you, you or possibly better virtual disgrace is holding the copyrights for the opencollar.at webside. Any other claiming to own any rights on texts and using them from opencollar.at is a clear violation\r\n\r\nBut if somebody else comes and uses the GPLd parts, even under some circumstances may use the apache licensed parts and distributes it without claiming that they own contents from opencollar.at then thats perfectly ok.\r\n\r\nAnd if that version becomes more popular then the virtual disgrace version then that version will become the \"official\" version"}],"action":{"name":"View Issue","url":"https://github.com/OpenCollarTeam/OpenCollar/issues/31#issuecomment-346859178"}}}

**Comment by WendyStarfall** [comment]
I'm aware of all that, but I appreciate it very much that you have explained it in simple terms, @pixelwork.

#### History...

The plan for opencollar.at was to license it [CC-BY](https://creativecommons.org/licenses/by/4.0/) if its creation would become more of a community effort.

The OpenCollar 4.0 version release would have been a great opportunity for that, as the whole site was re-created at this time. Unfortunately there was no interest coming from the community to help improving the site. Instead some parties created virtual books on the Second Life® Marketplace, for sale.

There was no time to sulk, the community became very annoyed when the same questions were asked over and over again, and our users needed docs more than drama and hostility in the OpenCollar group chat.

I was very disappointed, and as a result, have composed the new opencollar.at by myself.

#### Digressing now...

In matters documentation, there were also positive effects, because "for sale" guides floating around didn't disappoint or upset only me alone. See, where the user docs did not, the slightly increased complexity for building the OpenCollar did spark indeed a lot of community involvement.

Users started helping each other, we experimented together, we sat our "temple", on the floor of the great festival stage area that we had at the time, and built our collars and contraptions together, and suddenly "OpenCollar" was a community again.

**Comment by silentwar-resident** [comment]
wait a minute, i thought opencollar.at was originally belonged to founders of open collar, I recalled master starship was testing the communication to collar through the website?

**Comment by nirea** [comment]
No, we've had other web platforms but that site was created by Wendy.

**Comment by silentwar-resident** [comment]
Got it. Ty.
null

**Comment by silentwar-resident** [comment]
so the domain iteself not website belongs to wendy as well?

**Comment by CorwinDavidson** [comment]
CollarDB still has the web interface code and a re-write of the website / database that was dropped from the OpenCollar scripts

**Comment by nirea** [comment]
Going to stick with the wiki for now.  If people start clamoring for something prettier, we can revisit.
