### ISSUE TITLE
[Feature Request] Wearer-managed Trusted

### ISSUE THREAD

**Issue by Qaus-Sphene** [OpenCollarTeam/OpenCollar#318]
What version of OpenCollar are you using?
7.5

What behavior did you expect?
The ability for owners to give the wearer the privilege to add and remove other users to the Trusted list on their own.

What behavior did you see instead?
Wearers have no way to add/remove people from Trusted list unless they own themselves, which for many people might as well be like keeping the collar unlocked and restrictions unenforced.

**Comment by mistressohm** [comment]
A few thoughts:

1) Trusted is a grey area already - in terms of the RLV relay, it's whoever
owns the land/set out the devices.  From a collar standpoint it's a
personal thing - someone 'trusted' to play with the submissive but not own
them outright.  So while an owner should be able to veto a sub's choices,
the sub SHOULD have the choice in the first place.

2) Self-owned isn't unlocked.  It's the ability to unlock or revoke, when a
scene ends, rather than using a safeword.  In my case, I can set my collar
to specific groups when I enter a sim with BDSM play, so as to make myself
available to whoever comes along. But when I leave that sim, I can turn
Group access off (because out of that sim I have no need to play with
anyone associated with it.)  Some Owners want to be able to control their
subs to a fine degree.  That's great.  But as a switch, I can't be
bothering people to change my settings to match the scene I'm wanting to
participate in.

**Comment by Qaus-Sphene** [comment]
when i say 'might as well be keeping the collar unlocked' i mean you can unlock the collar at any point in time which removes some of the fantasy of being stuck in it and trivializes restrictions. having to resort to self-ownership to have agency over the user trust list is overshooting the level of agency i'm requesting. an owner can still set what people on the trusted list are capable of doing with regards to restriction exceptions, so i'm not entirely sure why wearers are 99% blocked from choosing who's in or out.

(for clarification i'm not speaking of trusted objects or relays)

**Comment by zontreck** [comment]
Anyone else want this feature? As @mistressohm said it would be a grey area if we were to make it so wearer could manage the trusted list once they have an owner set.

**Comment by SimplyNemz** [comment]
I think a better option would be to change the way adding Trusted folks to the collar works might be better? Make it so the wearer can add people to an approval list that the owner can then agree or dismiss. Owner is unable to add people, only approve. Gives the wearer the ability to pick who they are comfortable with but the owner a final veto.

**Comment by Qaus-Sphene** [comment]
Since the Owner already has control over what Trusted users can and cannot do with the wearer, I don't think it would override much of the Owner's control over the wearer. That said, I like @SimplyNemz's idea too. Basically anything that gives the wearer a degree of agency/autonomy between typical owner/wearer scenarios and own-self scenarios.

**Comment by zontreck** [comment]
.@Medea-Destiny @SilkieSabra what are your thoughts?

**Comment by zontreck** [comment]
We can do this as a proposed trusted user list, and the owner can then approve the new trusted users.

**Comment by zontreck** [comment]
Marking todo list for a future version. Removing from 8.0 project queue

**Comment by Qaus-Sphene** [comment]
aw i just updated and was looking for this feature :(

8.1 maybe?

**Comment by zontreck** [comment]
Yes. 8.1
