### ISSUE TITLE
Meshthemes and themes both not working properly

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#333]
Making this ticket to note that there is a major bug in both meshthemes and regular themes.

In the case of meshthemes, it seems to make linked prims visible when it should not.

In the case of themes, all exact issues are unknown.

**Comment by CallistaCharron** [comment]
After some discussion in-world I was asked to post this here: the problem with oc_meshthemes is that it cannot handle multiple prim objects properly due to the fact that no link number can be indicated in the .meshthemes notecard. The ApplyFace function in oc_meshthemes always sends the llSetLinkPrimitiveParamsFast command to LINK_SET. The result is that textures get applied to prims that should remain invisible, such as the leashpoint prim.

A simple fix would be to change the LINK_SET to LINK_THIS, which fixes the issue with the current version of the collar (7.4/7.5). But of course, this still effectively means the script cannot handle multiple prim objects; the 'fix' in this case would simply mean that it ignores all other prims besides the root/scripted prim, which is not very neat IMO.

I propose the following change to the ApplyFace function in oc_meshthemes. This change fixes the issue with the current version and is backwards compatible with the existing .meshthemes notecard, but allows for texturing the non-root prims any way you like. The .meshthemes notecard can be extended with additional lines that apply textures (like a transparent texture) to any link number in the set. LINK_* constants can be used too, for example using -2 as link number (= LINK_ALL_OTHERS) could be an easy way to apply a transparent texture to all prims except the root prim.

The prim number (or negative LINK_* set number) is given as the 8th (last) parameter in the list. When not given (or when given as 0 or 1), the texture will only be applied to LINK_THIS, i.e. the root prim, and leave the other prims untouched (which fixes the initial issue of the leashpoint prim appearing when changing themes).

The following line in .meshthemes would apply the default transparent texture to all prims except the root prim:

-1|8dcd4a48-2d37-4909-9f78-f7a9eb4ef903|<1,1,1>|0|0|0|0|-2

(zeros added for readability, these can be left out of course).

This is the changed function:

```
ApplyFace(string sRule) {
    list lParts = llParseStringKeepNulls(sRule, ["|"], []);
    integer face = llList2Integer(lParts, 0);
    string tex = llList2String(lParts, 1);
    vector color = (vector)llList2String(lParts, 2);
    float alpha = llList2Float(lParts, 3);
    
    // See http://wiki.secondlife.com/wiki/LlSetPrimitiveParams#PRIM_BUMP_SHINY for shine/bump values
    integer shine = llList2Integer(lParts, 4); 
    integer bump = llList2Integer(lParts, 5);
    float glow = llList2Float(lParts, 6);

    // START ADDED CODE
    // check if a link number is given, negative numbers can be used:
    // -1 = LINK_SET (all prims)
    // -2 = LINK_ALL_OTHERS (all except the scripted prim)
    // -3 = LINK_ALL_CHILDREN (not very useful perhaps, but possible)
    // -4 = LINK_THIS (just the scripted prim, same as not giving link number or using 0 or 1 as link number
    integer link = llList2Integer(lParts, 7);
    if ((link >= 0) && (link <= 1)) {
        // if no link number is set, or link number == {0|1}, apply to root prim (LINK_THIS)
        // otherwise, apply to the numbered link(-set)
        link = LINK_THIS;
    }
    // END ADDED CODE

    llSetLinkPrimitiveParamsFast(
        // START CHANGED CODE
        link,
        // END CHANGED CODE
        [
            PRIM_TEXTURE, face, tex, <1,1,0>, <0,0,0>, 0,
            PRIM_COLOR, face, color, alpha,
            PRIM_BUMP_SHINY, face, shine, bump,
            PRIM_GLOW, face, glow
        ]
    );
}

```

Feel free to use this, no credits needed, or come up with a better solution. The above will obviously break a .meshthemes notecard using specific link numbers when unlinking a collar and relinking it in a different order, but I think that could only be prevented by first indexing every prim by (unique) name, which is more involved than what I currently have time for.

**Comment by zontreck** [comment]
There is already a new theme script in progress. I'll post it later
