### ISSUE TITLE
Add Weld feature

### ISSUE THREAD

**Issue by zontreck** [OpenCollarTeam/OpenCollar#356]
**Question: Should we add weld**

![](https://api.gh-polls.com/poll/01EBA8A8ZH07859N5BT1G4A40H/Yes)

![](https://api.gh-polls.com/poll/01EBA8A8ZH07859N5BT1G4A40H/No)
![](https://api.gh-polls.com/poll/01EBA8A8ZH07859N5BT1G4A40H/I%20don't%20care)

RELATED PREVIOUS POLL #311

**Comment by zontreck** [comment]
This poll closes in 1 week from now

**Comment by SilkieSabra** [comment]
I changed my vote anticipating that the "weld" feature would work as follows in OpenCollar:  A menu button that activates the settings for GLOBAL=lock~1 (collar is permanently locked) and AUTH=norun~1 (runaway is disabled).  I don't know what could be done to make this "permanent" without using a settings notecard however.  The drawback to a settings notecard is that the wearer has to add the notecard which is a bit of a mood kill for "weld".

**Comment by zontreck** [comment]
The poll is not a question of how to implement, the technical details can be worked out later

**Comment by zontreck** [comment]
Also: Nothing in SL is permanent, it's the illusion that people are mostly after

**Comment by zontreck** [comment]
Less than 24 hours remaining

**Comment by jwenting** [comment]
In all the different systems that have such an option it always comes down to the collar destroying itself if the lock is opened or RLV disabled.
This is not something I'd ever want to see in OC as it is prone to failure.
Enter a no-script zone and the lock will open or RLV not work, causing self destruct. 
Or the collar can (thanks sl) get detached during a TP or by simply logging out and in again. Happens all the time.
Or there's a script crash and the collar needs to be reset in order to get it working again. 

In all those cases a "welded" collar would be a disaster. 

On top of that, rl it's insanity and just not done. Any real dom (or sub) who demands such a thing is such a massive red flag the relation would be over immediately. Which is for me the biggest reason of all to judge whether I want something or not.

**Comment by zontreck** [comment]
We would never put in code that would destroy a collar. Or make it unusable. There will be a way to unweld. Plus simply reseting scripts will undo the Weld

**Comment by zontreck** [comment]
Also on the note of script crashes... This feature would not be available until v8 anyway, and the collar will have a feature to reset and start crashed scripts. A mini version of this feature can be found on the Apps folder, oc_anticrash.lsl

**Comment by SilkieSabra** [comment]
Aria has a fairly detailed idea in her head about how the weld would work, maybe it would help to include a short concept description here.

**Comment by zontreck** [comment]
sure. Let me close the poll and i'll post that

**Comment by zontreck** [comment]
okay - removed the ability to vote on the poll.
So basically, we'll publish this as a app, the owner will need to click weld, and the sub will need to consent by clicking an I Agree button. Unweld will be available through the exact same app, however only owner can trigger it, so if the owner gets removed or whatever, then wearer will be able to unweld it themselves. The app by default will uninstall itself after use, but a updater can always be used to reinstall it.. Pretty useless if the wearer reinstalls it though while they have a owner as only CMD_OWNER will be able to click unweld... probably will have to make it uninstall itself if someone other than owner tries to use the menu to unweld, otherwise they'd have a useless app in the menu.

**Comment by Carlo-Negulesco** [comment]
Would it not be possible that the 'weld' menu is only visible the CMD_OWNER?

**Comment by zontreck** [comment]
Now in progress
