### ISSUE TITLE
Security Issue - LinkMessage and failsafe(1) calls

### ISSUE THREAD

**Issue by CorwinDavidson** [OpenCollarTeam/OpenCollar#44]
There is currently a security issue where any third party plugins could cause a large portion if not all scripts in the collar to delete themselves.

In many of the scripts you will find the following line in the link_message event handler:
```
} else if (iNum == 451 && kID == "sec") FailSafe(1);
```

This calls the FailSafe function which in turn has the following check:

```
FailSafe(integer iSec) {
    string sName = llGetScriptName();
    if ((key)sName) return;
    if (!(llGetObjectPermMask(1) & 0x4000)
    || !(llGetObjectPermMask(4) & 0x4000)
    || !((llGetInventoryPermMask(sName,1) & 0xe000) == 0xe000)
    || !((llGetInventoryPermMask(sName,4) & 0xe000) == 0xe000)
    || sName != "oc_settings" || iSec) {
        integer i = llGetInventoryNumber(7);
        while (i) llRemoveInventory(llGetInventoryName(7,--i));
        llRemoveInventory(sName);
    }
}
```

Which in general terms will delete the script and sometimes other items if the iSec value is 1.

The only thing a script would need to do is make the following call...
```
llMessageLinked(LINK_SET,451,'','sec');
```

I could not see any code path that generated this type of call in the collar source, neither now nor in the commit in which this code was introduced.

**Comment by pixelwork** [comment]
that only makes sense as a kill-switch triggered from the protected oc_root script.

we dont like you, we kill your collar... something like that. i for removing that possible iSec kill switch but keeping the other perm checks for now since they remind you as builder when you setup things with wrong perms. possible replace the llRemoveInventory thing by something that sends a message in chat about wrong perms and where they are wrong.

**Comment by silentwar-resident** [comment]
No kill switches….  Let make it warnings so they can have chance to fix it….

**Comment by pixelwork** [comment]
you possibly got me wrong on the kill switch part, i dont want any kill switch either, that "we dont like you, we kill your collar... something like that" war my idea of why VD introduced that part.

i am working on removing it in my 6.7 based fork and can provide a diff/pull request later for this fork if it is requested

**Comment by GarvinTwine** [comment]
I really have no idea where your conspiracy theory that we would want to destroy anyone's collars comes from. 

But let me enlighten you on this one:
Yes it is a "kill-switch" if you want to call it that, for the case that there is a time when the script is no longer needed/wanted in that non-root prim.
A possibly handy usage would have been to delete these scripts in case you want to go back to a "all in root prim" concept. (it just spares you to load a script into each prim to do the same thing).
It was added over a year ago for 6.4 after which lots of further updates were made and the idea of the new oc_root concept was not even born.
It just makes it easier to clean the prim in case you want to change your setup and update to a new design but not having it does not make it any bit more secure. That's what this is all about.
Of course you can say, I do not like the idea and remove it but please spare the conspiracy theory about destroying anything!

The moment you allow anyone to install a script into your item, they can do what they want in there, they do not need any "kill-switches".
So for this OpenSource project with an installer code presented to the world, anyone who does want to destroy your collar can make and give you an "updater" that does exactly that, no special "kill-switches" are needed for that that's simply the nature of it.

A very good example for this is what the contributor of this issue does himself for years:
He "sells" his CollarDB version 5.001 as update for OpenCollar 3.96 where it does then downgrade to his code which is based on OpenCollar 3.5 code.
https://marketplace.secondlife.com/p/CollarDB-Updater/4916353 
//CollarDB - rlvmain - 3.531
//CollarDB - menu - 3.520
etc.

It would also be nice to educate the moderators in "your" goup that the failsafe() function is neither malicious code nor does it have anything to do with who is creator of any item, but it is there, as you said yourself here 

>  perm checks for now since they remind you as builder when you setup things with wrong perms.

**Comment by CorwinDavidson** [comment]
I don't believe I ever attacked anyone in my post above.  I even specifically mentioned that the code fragment I was discussing had no calls, nor had any calls to it when it was added.

Regardless of the intentions for why it is there, it could be used by a THIRD PARTY.  Yes they could just as easily have code in a plugin or "updater" that deleted all scripts in the collar, or they could hide the call to this built-in kill code and whenever they felt like delete all scripts in the collar.

As it stands it is a possible security issue for the OC collar scripts.

As for the CollarDB scripts.  People who use it know it has a web database.  It stores nothing more nor less then what the web database OC had originally stored.  Nor was it a "downgrade" to anything as the code for every file had been touched and changes made, regardless of if I remembered to change the version in the comment at the top of every file.

**Comment by nirea** [comment]
A chat-based warning about permissions would be fine.

Making the collar self-destruct over it is not.

Even aside from that, the obscured nature of the code above (using raw integers instead of the much more understandable LSL constants) looks like someone's trying to hide something.  We shouldn't be doing that.

**Comment by nirea** [comment]
Let's replace FailSafe with this function:
```PermsCheck() {
    string sName = llGetScriptName();
    if (!(llGetObjectPermMask(MASK_OWNER) & PERM_MODIFY ) {
        llOwnerSay("You have been given a no-modify OpenCollar object.  This could break future updates.  Please ask the provider to make the object modifiable.");
    }

    if (!(llGetObjectPermMask(MASK_NEXT) & PERM_MODIFY)) {
        llOwnerSay("You have put an OpenCollar script into an object that the next user cannot modify.  This could break future updates.  Please leave your OpenCollar objects modifiable.");
    }

    integer FULL_PERMS = PERM_COPY | PERM_MODIFY | PERM_TRANSFER;
    if (!((llGetInventoryPermMask(sName,MASK_OWNER) & FULL_PERMS) == FULL_PERMS)) {
        llOwnerSay("The " + sName + " script is not mod/copy/trans.  This is a violation of the OpenCollar license.  Please ask the person who gave you this script for a full-perms replacement.");
    }

    if (!((llGetInventoryPermMask(sName,MASK_NEXT) & FULL_PERMS) == FULL_PERMS)) {

        llOwnerSay("You have removed mod/copy/trans permissions for the next owner of the " + sName + " script.  This is a violation of the OpenCollar license.  Please make the script full perms again.");
    }
}```

**Comment by TakatSu1** [comment]
Seconded on the proposed solution from Nirea.  I prefer telling them to being draconian (i.e. deleting stuff).  If I make a mistake I'd be rather annoyed if the scripts just started deleting things on me, just as I would be annoyed with a compiler that decided since I had a syntax error, it would delete some of my source files.  Just give me an error message, please! :)

**Comment by nirea** [comment]
So, weird thing.  Not only does FailSafe delete the script itself, it first deletes ALL notecards (inventory type = 7) in the prim.  Why?

**Comment by nirea** [comment]
oc_anim has this version, which first deletes all animations from the prim:

```FailSafe(integer iSec) {
    string sName = llGetScriptName();
    if ((key)sName) return;
    if (!(llGetObjectPermMask(1) & 0x4000) 
    || !(llGetObjectPermMask(4) & 0x4000)
    || !((llGetInventoryPermMask(sName,1) & 0xe000) == 0xe000)
    || !((llGetInventoryPermMask(sName,4) & 0xe000) == 0xe000)  
    || sName != "oc_anim" || iSec) {
        integer i = llGetInventoryNumber(20);
        while (i) {
            sName = llGetInventoryName(20,--i);
            if (llGetInventoryPermMask(sName,1) & 0x8000) 
                llRemoveInventory(sName);
        }
        llRemoveInventory(llGetScriptName());
    }
}
```

**Comment by nirea** [comment]
I just pushed https://github.com/OpenCollarTeam/OpenCollar/commit/8d9764b8f29dff927ecf0741d910db2ded8e166e, which replaces all versions of FailSafe with the saner PermsCheck I pasted above.

**Comment by nirea** [comment]
So the main remaining mystery is this line:

```
if ((key)sName) return;
```
The whole FailSafe check will be skipped if the script's *name* is a valid UUID.  Would be good to know how that was used.

**Comment by nirea** [comment]
Oh and also there's a filter on the animation deletion, to only delete ones with PERM_MOVE set.  Another weirdness.

**Comment by silentwar-resident** [comment]
Yeah big mystery… but seems Wendy did change failsafe again…  link to her changes:

view it on GitHub

**Comment by silentwar-resident** [comment]
Aye, I agree with ya 100% on this  we shouldn’t delete the scripts at all

**Comment by silentwar-resident** [comment]
Great.. that will solve this 😊

**Comment by WendyStarfall** [comment]
The FailSafe logic prior to https://github.com/OpenCollarTeam/OpenCollar/commit/8d9764b8f29dff927ecf0741d910db2ded8e166e was a neat, and compact block, that you can re-use in any other GPLv2 licensed script.

Its practical use and intent were well described in the upstream's git log in https://github.com/VirtualDisgrace/opencollar/commit/1888070fbbf52d4f1dfc74d88e7c33b9fb8a9bec on Oct 25, 2016.

You need to come to terms with the real world scenario, where this logic is applied when the builder moves the scripts from her Second Life inventory into her artwork's contents.

From years of experience I know, that issues won't be corrected by the builder as long as "things stick". Most don't have the technical experience, and don't think about end-user experience or experiences with future updates. They want to **add** something to their artwork, and if **adding** it works, it is good enough for them.

1. There is nothing gained for the builder when creating an additional step of work, where she has to remove the scripts from the objects contents, in order to correct things.

2. The builder, nor her end-users, are helped if they have to wrestle with defunct products that spam error messages out-of-the-box.

PS: I suggest that you adjust the title of this issue to reflect that FailSafe has something to do with correct builds, script nesting, and scripts nesting in the correct link, and nothing with end-user security concerns.

**Comment by SatomiAhn** [comment]
Another thing: this FailSafe()/CheckPerms() function adds a 3kB overhead in every script. I believe this is unwise, considering how critical memory can be (see issue #46).

Whatever this function does, is it worth increasing the probability of stack-heap collision crashes in memory-critical scripts ?
Cannot permissions be checked from a single script instead ? (less script time, less memory, fewer repetitions of code, ... so many advantages!)

**Comment by nirea** [comment]
I'd welcome a pull request that consolidates PermCheck into a single script
that loops over the others.

**Comment by nirea** [comment]
I've centralized PermsCheck into oc_sys and oc_installer_sys in https://github.com/OpenCollarTeam/OpenCollar/commit/c17c818d9279e92d4baf6814d512d4ccc80cc97f.
