### ISSUE TITLE
Relay Trust Owner does not toggle off

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#500]
In OpenCollar V 8.0.5, with the relay set to Ask, the Trust Owner setting when checked, allows the relay to act on auto if the object pinging the relay is owned by a collar owner.  When this is checked and then unchecked, however, it does not toggle off as expected, instead it continues to work on auto even if Trust Owner is unchecked.  This should also be tested with Trust Trusted.

**Comment by zontreck** [comment]
Elaboration on this issue after testing

Trust owner does toggle:  The new state however does not take effect because the relay remembers the source. Attempts at clearing the source and allowed sources list does not appear to affect this, however when resetting the script, the ask prompt does show as intended.

**Comment by SilkieSabra** [comment]
This is no longer an issue with the 8.2.3 relay
