### ISSUE TITLE
Should we have the "Disable Runaway" option in core code?

### ISSUE THREAD

**Issue by xxReyes** [OpenCollarTeam/OpenCollar#53]
What version of OpenCollar are you using?
7.0 Beta 3
What behavior did you expect?
Enhancement request: Not a defect

There is code in the collar currently that disables the option for the wearer to runaway - Is that something we want to include in core code?

**Comment by Athaliah** [comment]
This was not in the original code specifications for OpenCollar, and my opinion is the same on when this issue was raised in the past before version 4.0.   This "feature" to disable runaway was not to be included in OpenCollar, as anything that was done like that to affect someone's real life experience to the point where their only option was to log out and remove RLV, and then take off the item was not acceptable to me.  This is because the common second life person who's new to RLV does not know that they have this option to "escape" this way, and will instead think that their only options are either kept the bad collar owner, or quit Second life.   We don't want to scare away people from the whole platform of Second Life.     A collar is a symbol of something more.   If someone wants to have something on top of a locked collar, on top of RLV, then there is some issues that might need to be talked about, as a tool like collar scripts might not be the best thing for that person to wield.

**Comment by JAY1976** [comment]
Are we talking about totally removing 'Disable Runaway'? Because if we are then it is something I would be unwilling to put my name behind, I believe an option to add it via the .settings notecard is more than reasonable and I have always done background checks on the sub and the Dominant long before I add that option to any of my custom works even if it has been requested.  I myself will be adding it to the collar that I will be using during the collaring ceremony for my pet today (Sunday 10 December 2017), it is something we have taken time to discuss quite fully and are mutually agreed to,  I believe to totally remove this option would be a bad idea especially considering the level of commitment some subs wish to express to their Dominant, however, I have always advised caution and consideration before ever putting a collar using these settings on a submissive's neck

**Comment by silentwar-resident** [comment]
I think good idea if disabled runaway is set, give sub a warning of this and they answer yes or no. If no that setting is ingored.

-------- Original message --------From: JAY1976 <notifications@github.com> Date: 12/10/17  2:01 AM  (GMT-08:00) To: OpenCollarTeam/OpenCollar <OpenCollar@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [OpenCollarTeam/OpenCollar] Should we have the "Disable Runaway" option in core code? (#53) 
Are we talking about totally removing 'Disable Runaway'? Because if we are then it is something I would be unwilling to put my name behind, I believe an option to add it via the .settings notecard is more than reasonable and I have always done background checks on the sub and the Dominant long before I add that option to any of my custom works even if it has been requested.  I myself will be adding it to the collar that I will be using during the collaring ceremony for my pet today (Sunday 10 December 2017), it is something we have taken time to discuss quite fully and are mutually agreed to,  I believe to totally remove this option would be a bad idea especially considering the level of commitment some subs wish to express to their Dominant, however, I have always advised caution and consideration before ever putting a collar using these settings on a submissive's neck

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenCollarTeam/OpenCollar","title":"OpenCollarTeam/OpenCollar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenCollarTeam/OpenCollar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JAY1976 in #53: Are we talking about totally removing 'Disable Runaway'? Because if we are then it is something I would be unwilling to put my name behind, I believe an option to add it via the .settings notecard is more than reasonable and I have always done background checks on the sub and the Dominant long before I add that option to any of my custom works even if it has been requested.  I myself will be adding it to the collar that I will be using during the collaring ceremony for my pet today (Sunday 10 December 2017), it is something we have taken time to discuss quite fully and are mutually agreed to,  I believe to totally remove this option would be a bad idea especially considering the level of commitment some subs wish to express to their Dominant, however, I have always advised caution and consideration before ever putting a collar using these settings on a submissive's neck"}],"action":{"name":"View Issue","url":"https://github.com/OpenCollarTeam/OpenCollar/issues/53#issuecomment-350537233"}}}

**Comment by pixelwork** [comment]
i think there is a great demand for such a feature and we should not just close our eyes about it, a malicious owner can mod a collar anyways easily, comment out a few lines and its done.

but perhaps this should be in a plugin the sub has to install herself that deletes itself when you transfer the collar to a new owner or at least require active consent from the wearer giving a clearly understandable warning about what it means.

anyways even the other "popular" distribution does not do it in full consequence, you can tick "helpless" there but still can tick "clear all RLV restrictions" even in helpless mode

**Comment by xxReyes** [comment]
I mainly raised the concern because the way it is implemented is via the .settings notecard and it doesn't require informed consent from the person wearing the collar - i.e. 'gift' someone a collar with a modified .settings notecard and the runaway option is imposed without warning or notice. - I don't really mind that the option exists but like the 'spy' scripts I think we should validate that the wearer consents.

**Comment by JAY1976** [comment]
So basically the collar gaining consent from the wearer, kind of like I do before even making such a collar?...that might actually be a good idea :)

**Comment by Athaliah** [comment]
added edit: after seeing comments, I'd be open to a option where it was able to be enabled, but only with the collar wearers full consent & strong worded warning as a part of it and not be able to be done by a unscrupulous person handing a collar without any warning to the collar wearer, who then locks it on and is clueless that it was done. As long as there is that warning that the person is able to think a little bit that this may be important to know, then I'd be a bit more lenient on my thought on this design choice. Again, this is something for far in the future, and is not a current collar feature with any urgency as making sure that the collar is stable is first priority again. .

**Comment by silentwar-resident** [comment]
Yep agreed we need that and prompt agree or no agree if not agreed then runaway block is disabled.

Nathan
Sysop of Internetking BBS
Internetking@bbs.internetking.us
  
-------- Original message --------From: Athaliah <notifications@github.com> Date: 12/10/17  3:15 PM  (GMT-08:00) To: OpenCollarTeam/OpenCollar <OpenCollar@noreply.github.com> Cc: Silentwar Resident <internetking@internetking.us>, Comment <comment@noreply.github.com> Subject: Re: [OpenCollarTeam/OpenCollar] Should we have the "Disable Runaway" option in core code? (#53) 
added edit: after seeing comments, I'd be open to a option where it was able to be enabled, but only with the collar wearers full consent & strong worded warning as a part of it and not be able to be done by a unscrupulous person handing a collar without any warning to the collar wearer, who then locks it on and is clueless that it was done. As long as there is that warning that the person is able to think a little bit that this may be important to know, then I'd be a bit more lenient on my thought on this design choice. Again, this is something for far in the future, and is not a current collar feature with any urgency as making sure that the collar is stable is first priority again. .

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenCollarTeam/OpenCollar","title":"OpenCollarTeam/OpenCollar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenCollarTeam/OpenCollar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Athaliah in #53: added edit: after seeing comments, I'd be open to a option where it was able to be enabled, but only with the collar wearers full consent \u0026 strong worded warning as a part of it and not be able to be done by a unscrupulous person handing a collar without any warning to the collar wearer, who then locks it on and is clueless that it was done. As long as there is that warning that the person is able to think a little bit that this may be important to know, then I'd be a bit more lenient on my thought on this design choice. Again, this is something for far in the future, and is not a current collar feature with any urgency as making sure that the collar is stable is first priority again. ."}],"action":{"name":"View Issue","url":"https://github.com/OpenCollarTeam/OpenCollar/issues/53#issuecomment-350589894"}}}

**Comment by IalaAndromeda** [comment]
I don't want my name associated with a product that has this functionality. I've helped in the past too many newcomers to SL who were tricked into adding someone as their owner who then promptly locked their collar and removed all secowners including the wearer (if she were set at all).
Runaway is the best option for that, and a persuasive abusive dom can talk someone into allowing them to disable that as easily as allowing them to be added as primary owner.

Worse, it'd end up in the settings notecard where abusive doms could disable it along with having themselves as primary owner and the collar prelocked, which they then give out to newcomers, who unwittingly lock themselves into something they have no idea how to escape from (this was a prime reason why years ago the decision was made to make OC released collars no-trans).

**Comment by zontreck** [comment]
This ticket has been open since 2017 with no further replies. Closing this ticket
