### ISSUE TITLE
Third party plugins beginning with 'oc_' that are not full perm cause messages about wrong permissions

### ISSUE THREAD

**Issue by pixelwork** [OpenCollarTeam/OpenCollar#56]
What version of OpenCollar are you using?
I tried updating a 6.6.3 collar

What behavior did you expect?
With third party plugins messages i dont expect the installer or collar to yell at me about wrong permissions for third party plugins, they should be left alone and ignored

What behavior did you see instead?
I got various messages about wrong permissions with third party plugins like:

Clit Ring Gold/Silver 6.6.3 (pelvis): The oc_sobriquet script is not mod/copy/trans.  This is a violation of the OpenCollar license.  Please ask the person who gave you this script for a full-perms replacement.
Clit Ring Gold/Silver 6.6.3 (pelvis): You have removed mod/copy/trans permissions for the next owner of the oc_sobriquet script.  This is a violation of the OpenCollar license.  Please make the script full perms again.

The check just loops through scripts starting with the prefix "oc_" which some third party plugins also use, perhaps its better to have a list of core scripts and loop only through that list, this way you could tell "oc_xxx is missing for core functionality, please add oc_xxx"

What steps does someone need to take to reproduce the problem?
Use a collar that contains third party plugins that are not full perm and install at least Update 7.0 beta4

**Comment by nirea** [comment]
So the important distinction here is that it only affects scripts beginning with 'oc_'.  I don't think I want to encourage third parties to use that prefix, because it's likely to confuse users and end up with them asking us to support plugins that we can't.

So I'm leaning towards just changing the message.  Instead of saying "This is a violation of the OpenCollar license" we could say "All OpenCollar scripts must remain full perms."  Then it's on the third party to avoid making their script look like an OpenCollar one.

I'm open to the "explicit list" idea, and agree it could be a useful diagnostic tool.  I think it's a bigger change than I'd like to push into the 7.0 beta right now, though.

**Comment by Saraeva** [comment]
Prefixing a script such as "oc_", "vd_", or "cb_", has long been a method to distinguish between how third party plugins are applied to what scripted items. Script checking with a title name of "oc_", especially with many currently on the market, seems to be heavy-handed nagware, in my opinion.

**Comment by nirea** [comment]
Checking based on the oc_ prefix is the less heavy-handed alternative to the self-deleting FailSafe function that was in the scripts before.  First we replaced FailSafe with the gentler PermsCheck function.  Then Satomi pointed out how much memory was consumed by having it in every single script, so we consolidated to just having it in one script that would loop over the others.  Whether it checks based on a prefix or a list (or some combination) is an implementation detail that I'm open to changing, though not a high priority for me personally.  Pull requests welcome.

Are there really "many [scripts] currently on the market" that are affected by this?  I'm aware of only two: oc_hertzchen (spelling?) and oc_sobriquet.

**Comment by pixelwork** [comment]
oc_chatiquette and oc_spy from VD are two more i am aware of that use the oc_ prefix as well

**Comment by nirea** [comment]
What does chatiquette do?

**Comment by pixelwork** [comment]
chatiquette punishes you for saying the wrong things or not saying certain things

**Comment by Saraeva** [comment]
It would be a disservice to all users that have Chatiquette, Sobriquet, Spy, and Herzchen installed on their collars if suddenly they get messages about them being no modify, when obviously, there's nothing wrong with those scripts.

**Comment by nirea** [comment]
It sounds like chatiquette is a closed/proprietary version of the
"badwords" script that was once free and open.

Ditto for spy, which (according to diffs done by a couple people) seems to
have had GPL code pasted into it.  In that case, the current license
warning is actually correct.

Still, if someone wants to submit a pull request that uses an explicit list
of the OpenCollar scripts it's going to check, we can go that route.

**Comment by Saraeva** [comment]
The Badwords have always been Free and Open and Full Perms. They are included in Legacy Apps, along with Bell, Camera, Timer, Titler, Undress, and a couple of others.

**Comment by SilkieSabra** [comment]
The long term solution to this might be a third party plugin agreement that disallows using the oc prefix on scripts that are not full permission.

**Comment by Saraeva** [comment]
The long term solution is to create a white list of legacy third party plugins allowed to use the oc_ prefix that are not pull permissions. Alienating thousands of recipients of the Chatiquette, Sobriquet, Spy, and Herzchen plugins is not the way to go, if you're to retain usership.

**Comment by nirea** [comment]
If we're going to whitelist, let's whitelist the actual OC scripts, and not
the third party plugins.  We can't control what third parties do, but we do
control the naming of our own scripts.

Eva you mentioned "thousands of recipients" of those 4 plugins.  Do you
have an actual source of data on how many people are using them?  That
would be useful information.

**Comment by Saraeva** [comment]
Wendy has that information. Ask her.

**Comment by shark-net** [comment]
In the short term, might I suggest disabling the check on every init?

It makes sense to display this message when running the updater, as this is good information to have at that time. 

I'm currently using oc_spy and oc_herzchen, getting the same 4 paragraphs of warnings with each login is not useful anymore. Until I can find full perm versions of these plugins, I would like a way to disable these messages. Thanks!

**Comment by Saraeva** [comment]
I've tested this myself, and each time the collar is initiated, I get the same two lines about violation of the OpenCollar license. 

[18:47:02] OpenCollar Six: The oc_spy script is not mod/copy/trans.  This is a violation of the OpenCollar  license.  Please ask the person who gave you this script for a full-perms replacement.
[18:47:02] OpenCollar Six: You have removed mod/copy/trans permissions for the next owner of the oc_spy script.  This is a violation of the OpenCollar license.  Please make the script full perms again.

This is for each of the plugins. I can chalk it up in the rush to get 7.0 out the door, and cutting corners on testing and evaluation. However, if it was done with the intent to spam users of Virtual Disgrace products that have already been installed, I would like to cite your own number 1 guideline: "Guiding principle 1: OpenCollar is a labor of love, given freely to the Second Life community. While any designer is free to make a collar and put OpenCollar scripts in it, the project itself is nonprofit, and will not favor one designer over another."

Since the plugins pre-date the current owners of the OpenCollar group, those 4 scripts should be white-listed, in the spirit of "Be excellent to each other."

**Comment by nirea** [comment]
Certainly not done with the intent to annoy users, though I also wouldn't agree to it being an example of "cutting corners".  We do not guarantee compatibility with closed source, no-mod third party plugins, so they are not included in [our test suite](https://github.com/OpenCollarTeam/OpenCollar/wiki/Manual-Test-Suite).  I don't even own any to test with.

I do not like the fact that there are closed source, no-mod, for-profit plugins out there that use the oc_ prefix, making users think that we are responsible for supporting that code, or for making it closed in the first place.  That being said, I agree that the annoyance to users trumps that concern.

89b9d4fdfdf8f32f966788a78eb7baf91c455a51 refactors PermsCheck to use an explicit list of official OpenCollar scripts.

**Comment by kyrahabattoir** [comment]
On a sidenote, why is this check even there to begin with, the GPL license has no such requirement,

**Comment by nirea** [comment]
The OpenCollar license, since the earliest versions, has stipulated that the scripts must remain full perms, in addition to the GPL requirements.

**Comment by nirea** [comment]
Though a scripted check for these permissions first appeared in the FailSafe function that Wendy and Garvin added. That function would silently make scripts self delete if you messed up the permissions.  The new PermsCheck is a less heavy handed alternative.
