### ISSUE TITLE
Potential OC Cuffs Beta 2 as we shake out any bugs

### ISSUE THREAD

**Issue by Pingout** [OpenCollarTeam/OpenCollar#584]
What version of OpenCollar are you using?   8.0.5 OpenCollar Cuffs Beta 1 Ref: Pull #583 

What behavior did you expect? 

What behavior did you see instead? Script contains some debug notices

What steps does someone need to take to reproduce the problem?

**Comment by SilkieSabra** [comment]
#583

**Comment by Trinkitz** [comment]
The cuffs have been generally very good, but we have encountered a few issues with "access" and "permission" . For example, if I (default owner / wearer / no named owner on the collar) pose myself, then a Trusted person cannot change my pose, either arm nor leg chains. I think this is due to a wearer being a default owner, which of course out-ranks Trusted. Further:

If I am NOT a named owner, but have a named owner on the collar, and pose myself, a Trusted person cannot un-do that pose. Access to both leg and arm chains is not possible. The menu vanishes when you click pose. Even the wearer cannot change things in this set-up; only the collar owner can un-do things. We have yet to test Group access.

**Comment by Pingout** [comment]
Merged into V 1.0.0
