### ISSUE TITLE
Cuffs lock request

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#631]
This is a feature request for AddOn Cuffs V2:

Currently the wearer cannot lock the cuffs.  If the cuffs lock emulates the collar lock, the wearer should be able to lock them (detach=n) but not unlock them if the wearer is owned.  This would be a nice self bondage feature.

**Comment by Pingout** [comment]
The wearer can lock the cuffs if their owner has SyncLock set in the cuffs. The SyncLock option has the collar Lock/Unlock commands control the status of the cuff locks. Since the wearer can already Lock (but not Unlock) the collar, by setting SyncLock, the wearer can Lock, but not Unlock the cuffs.
