### ISSUE TITLE
relay vulnerability

### ISSUE THREAD

**Issue by tayaphidoux** [OpenCollarTeam/OpenCollar#633]
What version of OpenCollar are you using?
 8.1.00000

What behavior did you expect?
relay to not be affected by users on a sim without some kind of input or notification, but furniture is ok.

What behavior did you see instead?
for the past few months on occasion my avatar would be stripped of any item that was not locked with rlv i have seen a few others have this issue at the same time on the same sim 

What steps does someone need to take to reproduce the problem?
hard to say usually happens on occasion when my owner is djing or hosting at venustus with people coming and going often so i assume its a "drive by" relay snipe.

A solution would be to inform the wearer or owner of the interaction at least when they are not set to ask, this way if some one is doing malicious things they can be added to the block list and/or reported, this could be a toggle option so that those who don't want to be spammed when doing normal play engage with furniture

**Comment by Medea-Destiny** [comment]
Just to clarify - if I understand right, this is happening when you are in AUTO mode (and thus expected) but because it is a one-shot command, you are not 'grabbed' by anything and would like some indication of the source of the one-shot command?

**Comment by tayaphidoux** [comment]
that's the idea some way we can find out who is doing it it to allow the community a way to protect its self, i totally expect to be grabbed by furniture on a sim but people with tools to just do random things as they teleport about are a problem for the community, it would take  bit more research for me to under stand the menu setup to add such a function so best to put it up to the community to decide and/or get it out faster.

**Comment by tayaphidoux** [comment]
on a side note there actually isn't enough info to know if this person will affect ask i do plan to test by having ask enabled in the future.

**Comment by Medea-Destiny** [comment]
I'm not sure this necessarily needs to be something with a toggle, but it's going to take some thinking about how this should be implemented. 

The first thing is this could get spammy. I'd suggest that  if a source gets flagged to report to the wearer, the source is stored in a variable g_kLastFlagged or similar, and reporting is done only if the source!=g_kLastFlagged. This will mean that you'd only receive the message if you have already been notified of the item sending commands and no other item has been flagged since. this is pretty vital because otherwise a hud sending a whole list of commands in one go will spam the warning for each command. This variable should probably be cleared in on_attach.

Secondly it should be considered what causes an object to be flagged. Firstly, the flag should probably only be triggered by commands where comtype = "force" and source = NULL_KEY, which don't set a current restrictions (and thus no source which would appear in the menu).  

Architecturally there is an issue in that with the relay on auto, you're by definition accepting everything and no real consideration is given to the source. Should such flagging really be done for every object that passes a command? Probably not. There should be some kind of sanity checking for what kind of objects get flagged,  but obvious things like ignoring items owned by owner/trusted isn't something that can be done simply, because in auto mode we're not checking for command auth and don't have that information (relay does not store auth lists). We could relay a potential flagging through auth to check that if it's an important consideration.  It would also probably make sense to do a test for whether the item sending the command is an item the wearer is sitting on and not flag that.

**Comment by tayaphidoux** [comment]
> I'm not sure this necessarily needs to be something with a toggle, but it's going to take some thinking about how this should be implemented.
> 
> The first thing is this could get spammy. I'd suggest that if a source gets flagged to report to the wearer, the source is stored in a variable g_kLastFlagged or similar, and reporting is done only if the source!=g_kLastFlagged. This will mean that you'd only receive the message if you have already been notified of the item sending commands and no other item has been flagged since. this is pretty vital because otherwise a hud sending a whole list of commands in one go will spam the warning for each command. This variable should probably be cleared in on_attach.
> 
> Secondly it should be considered what causes an object to be flagged. Firstly, the flag should probably only be triggered by commands where comtype = "force" and source = NULL_KEY, which don't set a current restrictions (and thus no source which would appear in the menu).
> 
> Architecturally there is an issue in that with the relay on auto, you're by definition accepting everything and no real consideration is given to the source. Should such flagging really be done for every object that passes a command? Probably not. There should be some kind of sanity checking for what kind of objects get flagged, but obvious things like ignoring items owned by owner/trusted isn't something that can be done simply, because in auto mode we're not checking for command auth and don't have that information (relay does not store auth lists). We could relay a potential flagging through auth to check that if it's an important consideration. It would also probably make sense to do a test for whether the item sending the command is an item the wearer is sitting on and not flag that.

you bring up good points as to filtering some of them i didn't consider, and brought it up as an issue rather then just trying to implement it so that people can discuss it because i do agree with open being you accept all incoming communications, the idea of having it as a toggle or even part of the system in the first place is to not interfere with the open auto accept nature but to allow users to still take precautions against griefers without having to give up the sense of vulnerability to the fun parts of rlv.
