### ISSUE TITLE
Who clicked Collar

### ISSUE THREAD

**Issue by Catspawgat** [OpenCollarTeam/OpenCollar#69]
It may be nice to create a plugin allowing collar wearers to see who's clicking their collar.
This will allow subs to see who is trying to mess with them  as well as them notifying their D (Dom/Domme)
Maybe even a little more of an added bonus to display directly to wearer and owner

P.S I don't know how to select the label "Feature request"

**Comment by CorwinDavidson** [comment]
I can contribute this as an optional script.  It was written for the CollarDB fork so I would need to dust it off a bit and re-convert it work with the current OpenCollar.  By default it would notify the wearer and all owners.

**Comment by nirea** [comment]
I like the idea of letting it incubate as an optional plugin.

**Comment by SatomiAhn** [comment]
I do not like this much.
- as a dom/me: this feature would spoil the surprise element
- as a sub: it may display too much useless spam

A (better) variation on this idea:
Implement a command for displaying the log of the N latest collar usages (including time stamp, action, and name/uuid of collar user). N should be adjusted so that no memory error is ever triggered.

### What to log?
Logged actions could just be collar touches (using a touch_start event), but I believe
- not all touches are interesting (un-authed touches are just useless noise)
- other accesses should be logged (access through chat command for instance)

### Proposed implementation

All user interactions first go through either oc_com+oc_auth or oc_dialog. Thus logging LMs from these scripts should be enough to catch all collar uses.

Hence, the plugin should try to recognize some of the following patterns and log positive matches:
- a CMD_GROUP LM
- a CMD_NOAUTH LM followed by a matching CMD_GROUP LM (catches the fact that a group user was just authed into the collar system)
- a DIALOG LM (maybe redundant with the CMD_GROUP LM with "menu" command that triggered it)
- a DIALOG_RESPONSE LM (this is often the only chance to catch final actions, since all what follows is often handled internally by the target script)
- a DIALOG_TIMEOUT menu timeout
- others LMs ?

### Command for accessing the log

A single command should be enough to ask for the log to be printed. It should accept optional parameters for filtering.

### Other considerations
- Among CMD_SOMETHING LMs, only CMD_GROUP ones should be logged: owners and trusted people should be above being spied by the wearer.
- Probably, even for public access or group users, it would be fair to warn the user that they are being logged.

**Comment by SatomiAhn** [comment]
I just noticed the feature requested by @Catspawgat already exists.

The command is "busted". It toggles the touch notification on/off. There is also a setting parameter: "touchNotify".

I guess this closes the topic?

**Comment by Catspawgat** [comment]
How do I activate this if it already exists and how do I set it to notify owner? 
I requested this feature because many people have a script the add to their OC collar that notifies them when the collar is touched. But want their collar owners to be notified if someone is clicking their collar.
So I may not know all the collar functions well...it seems the many people I know, also don't know how to activate this

**Comment by CorwinDavidson** [comment]
in locak chat type:
/1<prefix>busted on

There is no built in notification for owners

**Comment by Catspawgat** [comment]
Thank you Corwin
Satomi, I tested this feature. It DOES notify the wearer of the collar but does not notify the owner

**Comment by SatomiAhn** [comment]
You are right, this was the second half of your feature request, which I forgot about. Feel free to re-open.

**Comment by Athaliah** [comment]
Reopening issue, as it appears it was closed prematurely.    Feature request is for the owner to get the notification, not the collar wearer.

**Comment by GarvinTwine** [comment]
The VirtualDisgrace new spy has such a feature (reporting the owner(s) about non authorized to try to interact with the collar) it is currently for free available on the MarketPlace.
Just search the MarketPlace for "opencollar spy" and it should show up as one of the first hits.

Here is what it all else can do: http://www.opencollar.at/spy.html

**Comment by nirea** [comment]
Is that script GPL, Garvin?

**Comment by Godwrath1** [comment]
I could have sworn the spy script already had that option in it....

**Comment by pixelwork** [comment]
Spy - 161029.1 which has been released as Spy version 4.4 inworld under the GPL license by virtualdisgrace already had that option, though it never has been added to github but since it is GPLd it can be used, its derivative work from subspy which can be digged out from the git history and can be checked via "diff"

**Comment by RayZopf** [comment]
I'd love to see that version 4.4
as I own 4.3 (GPL) and 4.5 (changed to VD license)

**Comment by WendyStarfall** [comment]
There are several spy plugins floating around. Most importantly though, the following:

**The OpenCollar - subspy from the early OpenCollar 3.x days**

- is now in violation with the Second Life Community Standards / ToS
- had good contributions by @RayZopf (as he is participating in this issue)

**The State of the Art Spy App**

- was proprietary to me and only available in the original "Disgraced Version"
- was proprietary to me and shared cost-free as plugin for late OpenCollar API 3.9
- was then open-sourced and then for sale as plugin for late OpenCollar API 3.9

**The Virtual Disgrace™ Spy 4.0**

- derivative of some code that I open sourced as plugin for OpenCollar API 4.0
- was available as open-source and for sale as a plugin for OpenCollar up to version 4.2.0

**The Virtual Disgrace™ Spy Six**

- was proprietary to virtualdisgrace.com and available for early OpenCollar API Six
- was then open-sourced, re-mixed with Spy 4.0 and available for late OpenCollar API Six

**The Virtual Disgrace™ New Spy**

- was available cost-free as open source with both "transferable" or "copyable" variations included

The relevant differences in licensing are only in between "proprietary" and General Public License, version 2.
The relevant differences in Second Life DRM rights, are in between "full perm", "transferable" and "copyable".

The early compile of "New Spy" was released with the wrong copyright header, but the source could be accessed normally. As its source code can be read in the "compiled but not running" script, I see no reason to publish it on GitHub, although you are most welcome to ask me for a copy and I'm happy to sell it to you.

A word of caution: @pixelwork is not associated with our operation, and can't possibly tell with sufficient accuracy which code is derivative of one the many different variations of spy plugins, and which one is not.

And on a side-note; I've been looking through this repository and there are references to virtualdisgrace.com missing in several scripts that were originally created, or fully refactored, by virtualdisgrace.com members.

**Comment by nirea** [comment]
So Wendy, you're saying there's a "New Spy" script out there with a header indicating that it's GPL, but it really wasn't GPL?

**Comment by zontreck** [comment]
I have written a plugin to fix this issue if interested, i can file a pull request. It is completely opensource and under the GPLv2

**Comment by zontreck** [comment]
I'm going to look into adding a option in the menus for touch notices and provide the option for wearer and owner. Since the present way of doing it : chat command. Is not obvious to everyone

**Comment by zontreck** [comment]
No plugin is needed for this. The feature is implemented and can be enabled by chat command
