### ISSUE TITLE
Strict sit stays on

### ISSUE THREAD

**Issue by Surssin** [OpenCollarTeam/OpenCollar#711]
OpenCollar version 8.2.1000

A couple of times now, my owner has turned strict sit on, then later turned it off, yet the collar still behaved as if it was on. Thus far, the only way to clear it is to relog. Turning it back on and back off did not seem to clear it, and it has happened multiple times.

I again feel like that's pretty much all there is to my feedback on this one.

**Comment by Medea-Destiny** [comment]
I am unable to reproduce this.

@Surssin Can you provide a step-by-step example that will reliably cause this problem? Has anyone else observed the same issue?

**Comment by Surssin** [comment]
@Medea-Destiny I will try it again and add my reply when I get the chance. It may be a little bit before I can take the time to test test and test again to get you that step-by-step process, but I'll try not to make you wait too long.

**Comment by Surssin** [comment]
@Medea-Destiny Ok, here we go. step by step;

Test steps 1:
Turn on strict sit.
Force sit me.
Unsit me.
Turn strict sit off.
Now any time I sit, I can't unsit and "unsit" is listed on my restrictions. Relog required to clear.

Subsequent tests with these steps: Same steps. worked just fine.

test steps 2:
Turn strict sit on.
Force sit me.
Turn strict sit off.
Unsit me.
Now any time I sit, I can't unsit, and "unsit" is listed on my restrictions.
Hit Unsit while Strict sit still off. Restriction remains and I get the "unsit temporarily overridden" message.
Turn Strict sit back on.
hit unsit while standing.
Restriction cleared.

Test steps 2 were repeated a few times, and it went like this every time.

**Comment by Medea-Destiny** [comment]
@Surssin Thanks for the response. I am unable to reproduce the problem with the steps described in test steps 1, but can in test steps 2.

The issue is changes in the strict sit restriction being placed only at sit/unsit time when the strictsit setting is on, so switching it off while sitting was leaving it stuck. Can you contact me in world (secondlife:///app/agent/18032323-4a80-47f8-8aaf-cd500d8f6cea/about) and I'll send you a copy of the oc_rlvextensions script with a fix in for this, to confirm it works as it should in all situations now? Thanks.

**Comment by Surssin** [comment]
Seems like the fix works. I haven't seen any other bugs or issues pop up in its place as of yet.
