### ISSUE TITLE
Lock Core intermittently misspelling .core or failing to lock attachments

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#713]
This takes some explaining.

A user queried in OpenCollar that when Lock Core is active, a trap or chat command issuing an attachment on the same attachment point as an item in the core folder will still displace the supposedly locked item.

I was unable to duplicate this on my viewer.   However the user was able to show that her test was accurate.  She and I both have the same version of RLVa and same version of Firestorm (Firestorm 6.4.21 (64531), RestrainedLove API: RLV v3.4.3 / RLVa v2.4.1.64531).

I asked for some testing help in R&D and Zaleficent responded.  She does not have a github account so she was kind enough to write her investigation on a notecard which I paste here.  She is using Catznip R12.3.  

Summary:   oc_outfits is intermittently failing to detect the version of RLVa and this is causing core either to fail to lock at all, or to fail at the point the unwear command is sent.

-- Zaleficent's Report.  --

"I tested and got the same issue, checking the RLVa debug messages, I found the reason the .core folder wasn't locking was because the rlva command string sent by the collar was trying to lock "outfits/core" not ".outfits/.core".

After some more testing I decided to peek into the script to find the rlva command string generation code and see what was wrong.

line 308 onwards...
[code]
string GetOutfitSystem(integer iCorePath){
    if(g_iRLVa){
        if(iCorePath)return ".outfits/.core";
        else return ".outfits";
    }else{
        if(iCorePath)return "outfits/core";
        else return "outfits";
    }
}

string GetFolderName(integer iCore){
    if(g_iRLVa){
        if(iCore)return ".core";
        else return ".outfits";
    }else{
        if(iCore)return "core";
        else return "outfits";
    }
}
[/code]

This is detecting RLVa vs. RLV.
    
So more digging and...
[code]
    state_entry(){
        llMessageLinked(LINK_SET, ALIVE, llGetScriptName(),"");
        llListen(999988, "", llGetOwner(), "");
        llOwnerSay("@version=999988");
    }
    listen(integer iChan, string sName, key kID, string sMsg)
    {
        if(llSubStringIndex(sMsg, "RLVa")==-1){
            g_iRLVa=FALSE;
        }else g_iRLVa=TRUE;
    }
[/code]

The code assumes that RLVa users all use the same version of RLVa and that its version number will never include ".1"

So, the code is failing because it is falsely identifying any version of RLVa that has .1 in it as RLV not RLVa...
    
This affects anyone using Catznip R12.3 by Kitty Barnett, and possibly older versions of FS (say the last windlight version for EEP haters) or any future viewer with a newer RLVa version that happens to have .1 in its ver number..."
            
Zalificent...

**Comment by Medea-Destiny** [comment]
There's no version check in this code -- the listen event checks for the presence of the string "RLVa" as a substring of the version response message and setting g_iRLVa to FALSE if it is not found or TRUE if it is found.

This is check is happening in the default state of the script. When the script receives the startup message, it moves to the active state. My guess is what is happening here is that the collar is sometimes entering the startup phase before the viewer has had time to send the version response string, and thus the version check is never happening and g_iRLVa is never flagged TRUE.

We should probably be feeding this from the version check performed by oc_rlvsys rather than doing a duplicate version check here (and in every other place where a script needs to know), and should definitely not be doing it in the default state regardless. This is a script that would benefit from significant refactoring anyway.

**Comment by SilkieSabra** [comment]
Zaleficent reports (sorry for second hand info) that if you change viewers to an RLV viewer and update or reboot the collar on that viewer, the changed spelling (core not .core) is preserved when relogging again on fs.

Quote 
[14:02] Zalificent: if you change viewers, and say update the collar or reboot it on the bugged viewer [not fs]
[14:02] ròan (silkie.sabra): ok
[14:03] Zalificent: it keeps the wrong outfot/core names when you log in again on fs

**Comment by SilkieSabra** [comment]
This was fixed with pr to the 8.3 version branch
