### ISSUE TITLE
FYI: differences between 7.0 Distributed/Updated/Collarized

### ISSUE THREAD

**Issue by Psych0babble** [OpenCollarTeam/OpenCollar#75]
I'm uncertain if this is as intended, but here are the differences I found between the different collar types for 7.0:  Distributed, Updated (from 6.4), and Collarized versions.  I'm uncertain if there is an actual version here or if things could be made uniform across the board.

https://gyazo.com/f1c4770447ba263d61022bba185de618

Differences between Distributed and Updated: 

1. The distributed collar's mesh was no transfer, where the upgraded was full perm.  
2. The theme config files and scripts differed.  
3. There were two .settings files in the upgrade version that were not in the distributed version.  
Picture: https://gyazo.com/529b39dd82504d15eaca8ed91ca5cb61
My assumption here is that the themes need to stay the same for the old opencollar 4 to 6 since they are made for that specific mesh.  I was also told the settings file needs to be removed from the main prim since is needed in the same prim as the oc_settings script if its used.

Differences between the Distributed and Collarized:
https://gyazo.com/0932203012508ee13a767ab1941ed962
The cube in the center is the leashpoint, but All the other cubes were placed off to the side left side of the wearer.  I moved these to the center.  The leashpoint was named "leashpoint".  The animations prim was named "Childprims", and the oc_dialog script prim was named the same as the primary prim.  All other prims were just named Object.  I went ahead and renamed these prims to the old style: Animator, OpenCollar, RLV, Settings, and Auth, like the Distributed model.

Hopefully this helps!

**Comment by nirea** [comment]
Hi, thank you.  I've been meaning to rename the links in the set in the updater.  Silkie ticketed that at https://github.com/OpenCollarTeam/OpenCollar/issues/68.  (In the default collar it's already been done.)

The centering of the leash point is probably not something we should change.  The rezzing of prims when using oc_collarizer is actually done by the same oc_transform_shim script that also handles upgrading 3.x collars.  Most 3.x collars have their root prim as a little ball that sits in front of the main band of the collar (since the root prim used to be the prim used as the particle source).  So the oc_transform_shim rezzes the leashpoint right on top of the root prim, and the scripted prims in a column in the center, which means that the majority of people upgrading from 3.x won't have to reposition anything.  This does mean that most designers using oc_collarizer will have to move the leashpoint and other prims after installation (though it will vary depending on the position/rotation of the root prim in their creation).

The updater (and collarizer, which just triggers the updater) do not install any .settings or .themes notecards, since (as you note) those are specific to the mesh and the user.

You mentioned that the theme scripts (not just notecards) also differed.  The updater actually includes two theme-related scripts: oc_themes and oc_meshthemes.  The creation of the oc_meshthemes script was necessitated by the fact that the new distributed design is a single mesh object, and theming it requires applying different appearances to each face.  The old oc_themes script doesn't support face-specific appearance, however.  I also thought it was needlessly complicated.  So oc_meshthemes is intended for collars that are single-object meshes.  The oc_themes and oc_meshthemes scripts are scripted to avoid conflicting with each other.  They look for the presence of .themes and .meshthemes notecards, respectively.  oc_meshthemes will delete itself if .meshthemes is not present.  oc_themes is a little more conservative, only deleting itself it .themes is not present but .meshthemes is.

**Comment by nirea** [comment]
I've fixed the naming of the child prims in the updaters given from the inworld vendors.  The other differences that you note are intentional.  Thank you again for the report!

**Comment by Psych0babble** [comment]
Thanks Nirea!
