### ISSUE TITLE
Feature Request: 'Adjustable' TempOwner privilege/auth level

### ISSUE THREAD

**Issue by MuttMode** [OpenCollarTeam/OpenCollar#766]
What version of OpenCollar are you using? 8.2.1

Capture App! Totally Capturable!

Could a feature be added to change the access/auth level of the captor?
It would default to current Tempowner/Trusted but would have an option (could even be hidden and only accessible by chat command if you all think it's going to cause a bunch of problems for support requests from new wearers) for the captor to be given Owner status.

**Comment by mistressohm** [comment]
The issue with Temporary access being elevated is that the higher you get,
the more 'permanent' access the person has.  So requiring a submissive to
actually add someone into the permanent Owner or Trusted role is a safety
measure.  That said, a sub can do this at any time:

/1 <prefix> add [ owner | trusted] <name or UUID>

The /1 channel is available even when chat-blocked.
The prefix ensures that the wearer's collar (and no one else's) will
respond.
ADD is the command.  One can also REMOVE if necessary.
Choose Owner or Trusted as the access level.
State the name or UUID of the potential Dominant.

for example:

/1 be add trusted silkie.sabra

would add Silkie/Roan to my collar, which I've done a few times for her to
test issues.

If a submissive is perfectly OK with being at the mercy of complete
strangers all of the time, there's always the Public option, or Group
option if they need to restrict potential dominants to members of a group.

Capture Mode is a specific roleplay option, that of being kidnapped/coerced
into service.  Changing a Captor into an Owner should take time, multiple
sessions, and lots of getting to know each other OOC (just as should any
D/s relationship, because that's what it is, a relationship.)

While it wouldn't be difficult to set the Captor access level much like
Trusted or Owner (exceptions, access to apps, etc), there's the question of
whether such options would be a Good Idea on the whole, especially when
there's a perfectly viable way for any sub to add someone to their access
list.

**Comment by SilkieSabra** [comment]
This is superseded by pr #971 . If there are still unaddressed issues, please open a new issue.
