### ISSUE TITLE
Conflict when Wearer is also Trusted

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#774]
In 8.2.1, you can check Wearer Trust in the Access menu.  This should allow the wearer to add Trusted and works as expected.

However, you can also press + Trust and there's an option there to select Wearer.  When someone does this, the collar treats the Wearer at the Trusted rank instead of wearer.

This means among other things that they can no longer see the Access List, or add other Trusted, and are denied Access to Runaway.

Proposed Solution:  Remove the Wearer option from the + Trusted menu.  I can see there might be a use for these restrictions but on the whole it is confusing and might be difficult to retrofit to the specific condition of Wearer is also Trusted.

**Comment by Medea-Destiny** [comment]
Potentially a complicated issue. There are functions (seeing access list, runaway and others not mentioned) that wearer NEEDS to be able to access. These are currently dealt with by checking if access level is wearer. As trusted provides access to things wearer doesn't have be default, it is in theory a higher access level than wearer. Removing the option to allow wearer to be trusted is a reduction in functionality, but as we have a simplistic level system for access rather than anything granular, we would either have to retrofit a new access schema which would be a huge task (though useful) or go through all the options that allow wearer level access and do a key check to identify wearer rather than checking access level.

Can people think of situations where trusted gives wearer functions they do not have otherwise? I guess undoing restrictions that have been set by another trusted user? Anything else?

**Comment by KristenMynx** [comment]
Isn't the checkmark "Wearer Trust" duplicate functionality to  + Trust, >Wearer< ?  If so removing +Trust, >Wearer< is not a reduction in functionality.  

If it is not the same, then I'll go back and see if i can decipher the difference by reading and understanding the code better.

**Comment by SilkieSabra** [comment]
Picking this issue up again, Wearer Trust does not duplicate + Trust because it allows a wearer to add Trusted and set public access.  Neither of these things can be done with Trusted access.  However, I can't think of anything Trusted *can* do that the wearer can't, except grab the leash, and several things the wearer can't do anymore once added to Trusted.  Most users assume that adding the wearer to Trusted gives them more control over their collar, not less.  In fact, it gives the wearer less control, and it's also a security hole because wearers lose the ability to alter other settings and use Runaway, when they have not been asked to accept that loss.  Having both "Wearer Trust" in one place and "+ Trusted > <WEARER>" in another leads to confusion.  People think it's the same thing when it's not.  If anything it's caused more people to add wearers to Trusted access, thinking they are setting Wearer Trust.  So to my mind, having the wearer as an option in + Trusted is not a functionality, it's a bug.  It should have been removed when Wearer Trust was added, as I thought would happen back then. 

Now that we are looking at an 8.2.2 release, I'd like to remove this button and think about improvements to Access throughout the collar for 8.3.

**Comment by Medea-Destiny** [comment]
There are a significant number of commands that are accessible to trusted but not wearer. Thus adding wearer to the trust list grants additional powers to the wearer. The idea that it gives the wearer *less* power is an artifact  of the way that auth is handled. Auth will provide the highest value that a user is granted, so a wearer who is also on the trust list is given CMD_TRUST auth level. That sounds right, but raises an issue when instead of using a test for whether someone has a sufficient auth level, they have a particular auth level.

To be specific, by design we have auth levels in a descending scale. CMD_OWNER is 500, CMD_TRUSTED is 501, CMD_WEARER is 503. This clearly indicates that CMD_TRUSTED is _supposed_ to be a higher auth level than CMD_WEARER. However there are a number of things we need to ensure the wearer can always access. Normally this has been done by checking if auth == CMD_OWNER or CMD_WEARER, to exclude people who are CMD_TRUSTED. Obviously this doesn't make sense if the user is _both_ CMD_WEARER and CMD_TRUSTED. Because our auth system is relatively crude and doesn't allow for multiple auth values for a single user, this method of checking is not effective in all situations.

In cases where we want to ensure that the wearer of the collar has access, we shouldn't be using CMD_WEARER. That's fine for  a range of auths, for example if(iAuth>=CMD_WEARER && iAuth<=CMD_OWNER) will be true for the range of auths between owner and wearer (500-503). However to check specifically if we're dealing with the wearer, we can confirm via key and avoid this problem altogether, for example if(iAuth==CMD_OWNER || kAV==g_kWearer) will pass if the user has owner auth, or if they are the collar wearer.

My fixes in #834  apply this to oc_core, which is where most of the main issues mentioned above reside. This has the advantage of not changing the functionality of the collar, removing powers to people who already have them, or changing the ranking of auth levels that has existed since OC began. It has the disadvantage that it is an incomplete fix -- there are other scripts that need this treatment. However that's a matter of fixing what is in essence a long-existing bug found in a number of different locations throughout OC.

**Comment by mistressohm** [comment]
I'd actually use an "OR Wearer()" construction for any and all permissions
that a wearer should always have.    That way, if they aren't a wearer, and
don't have the proper level access, the check fails.  If they aren't the
wearer but DO have access, the check succeeds.  If they are the wearer,
their access level is immaterial, the check succeeds.

Leave OR Wearer() out for anything that they need to be Trusted or Owner to
have, and wearing the collar doesn't really factor into it.

For specific things that ONLY a Wearer should have (runaway, positional
settings, perhaps?) then "Wearer()" would be the only check.  No one else
gets access, period.
