### ISSUE TITLE
OC7 Leashes, Leash Posts, and the 'GrabbyPost' not compatible

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#78]
What version of OpenCollar are you using? 7.0

What behavior did you expect? 
The 'Grabbypost' to leash a collar on collision or via the 'scan' option by touching the post.   ALSO expected old leash behavior with the ability to click on a leash post to pass a leash to the post

What behavior did you see instead? 
GrabbyPost communicates on the wrong channel to interact with OC7. OC7 does not return a 'pong' message on the post's channel, but rather uses an avatar specific channel. Clicking on a leash post with a leash in hand results in nothing happening, leashes do not 'transfer' to leash posts.

What steps does someone need to take to reproduce the problem? 
Attempt to use an OC GrabbyPost or wear a collar and have someone(or themselves) hold their leash before clicking a readily available leash post.

**Comment by nirea** [comment]
What grabbypost script are you using?  Can you paste the source here?

**Comment by boundtight** [comment]
Same as the one that's listed here in the tree, src\spares\oc_grabbypost.lsl

Here's a copy just in case

[oc_grabbypost.txt](https://github.com/OpenCollarTeam/OpenCollar/files/1584997/oc_grabbypost.txt)

**Comment by SilkieSabra** [comment]
I recall a security issue with the grabby post, which involved a sit teleport or force teleport on public access.. the work around to allow the grabby post to work without the relay, also allowed for a weapon that was created that could force teleport anyone with the compatible access setting to any region on the grid.. the weapon was used for a short time as a traffic building ruse, are we sure we want to reintroduce the grabby post?

**Comment by boundtight** [comment]
There's no sit target in the grabbypost anymore, it just sends a leash request to the collar...which doesn't get answered by the collar for two reasons. 1) the grabby post communicates on the wrong channel to even reach the collar, but if that is fixed then 2) the collar no longer answers pings on the object's channel but rather sends a pong on it's own hud channel. This issue goes beyond just the grabby post since the old style of leashing (clicking on a leashpost to transfer a held leash to it instead of using the 'anchor' chat command or burrowing into the menus) also no longer functions.

**Comment by KristenMynx** [comment]
I'm sure I could make this work again.   I'll wait for guidance @nirea, whether it should be implemented.

**Comment by nirea** [comment]
I'm a little unclear on @SilkieSabra's reference to a relay.  Originally the grabby post was just a demo of objects sending commands to the collar, and didn't use RLV at all.  It sounds like it must have evolved into something else later, but I don't know all the features it later included.

If those features are well known, and people really want them, then yeah let's fix this up.  If they're not well understood, then let's just implement the bare minimum that the grabby post started with (if you bump into it, and its owner has some level of authority in your collar, then it should leash you to itself).

@KristenMynx you rock.

**Comment by KristenMynx** [comment]
So I've finally gotten time to work on this today.. 

The collision function works fine now (in my first iteration of simple fixes)

The original menu "Scan" function in this grabby post would scan for avies and only show a list of avies that replied to a :ping, with a :pong.    With the current OC7 (and pretty much all newer ones) it can't operate this way.  Instead, the best that can be done is to show all avies in range, and then try to leash from that list, which of course, some or most will simply fail authorizations.

So here's the why:

Many iterations ago the ping reply was changed (along with all the other comms) to use llRegionSayTo().  Generally a good thing.    Here's the relevant code in oc_com:
###
            link_message(integer iSender, integer iNum, string sStr, key kID)
            .
            .
            .
            else if (sStr == "ping")
                // ping from an object, we answer to it on the object channel
            {
                llRegionSayTo(kID,g_iHUDChan,(string)g_kWearer+":pong"); // sim wide response to owner hud
             }
###

kID here is the authorized avatar UUID (the owner of the object that sent the ping)   The original object UUID is not available, therefore llRegionSayTo() cannot reach the grabby post object.

There really is not a good fix.  Ping replies were probably conceived to work with remote hud (old name: owner hud) (also note the comment)   Since llRegionSayTo() works with huds its not a problem for that.

So I'm proceeding with removal of expectations of :pong, and moving forward with what could be perceived as a "noisy" Scan menu item in the grabby post.

If someone knows how to recover the original sending object UUID within the stream of permissions checking link messages and channel messages, -or- if we'd choose to let ":pong" be done as a llSay() or llShout() there could be a better fix.    Both fixes would require a change to oc_com as well.

**Comment by CorwinDavidson** [comment]
the line in oc_com that causes your problem is before that. it is https://github.com/OpenCollarTeam/OpenCollar/blob/8aef79a784a14a95baf9d94164290b29eea03821/src/collar/oc_com.lsl#L376-L377

The CMD_ZERO auth check should not include the llGetOwnerKey call it should just be:
```
llMessageLinked(LINK_AUTH, CMD_ZERO, "ping", kID); 
```

The other issue is that the grabby post uses the older "ping" and not "<wearer_uuid>:ping" message
https://github.com/OpenCollarTeam/OpenCollar/blob/8aef79a784a14a95baf9d94164290b29eea03821/src/spares/oc_grabbypost.lsl#L246
which should be:
```
llRegionSayTo(k,channel,(string)k+":ping");
```

You can see the changes / fixed version here:  https://github.com/CorwinDavidson/OpenCollar/commits/grabby_post_fix

Feel free to update your PR with the changes after testing / verifying

**Comment by KristenMynx** [comment]
@nirea My grabby post changes have been merged.. but @CorwinDavidson's changes are better.   My concern is that it requires a change to oc_com, and so the grabby post wouldn't work until that became main stream in world.    I would also want to trace through (which i'm sure @CorwinDavidson, did) to verify there aren't any strange ramifications based on assumptions made by CMD_ZERO/AUTH.   Do we know exactly which devices use :ping?

**Comment by CorwinDavidson** [comment]
I'm going to say it's not many as the oc_com ":ping" processing was broken for auth checking for standalone items like the grabby post.  I'm a bit rusty on my scripting but I think it would have worked if the item was an attachment.  My fuzzy memory seems to be thinking that attachments can hear llRegionSayTo messages sent to the avatar they are worn by.   And checking the wiki.. yes this is correct for any channel other then 0.

**Comment by KristenMynx** [comment]
ok.. I say we go with @CorwinDavidson's fixes, including the oc_com change.    Two paths are available.   1)  revert my pr, and have @CorwinDavidson submit one.    2)  I could simply do a manual reversion by starting over with the orginal grabby code, and make the changes, and submit that as a PR.

**Comment by CorwinDavidson** [comment]
Or I just submit a PR (#115) that changes the code to be what it needs to be.

**Comment by KristenMynx** [comment]
@CorwinDavidson looks good.

**Comment by nirea** [comment]
I just merged @CorwinDavidson 's PR.  Are we good to close this?

**Comment by KristenMynx** [comment]
I'd say yes.
