### ISSUE TITLE
Stack-Heap Collision in oc-rlvextension

### ISSUE THREAD

**Issue by DeaEnyo** [OpenCollarTeam/OpenCollar#782]
What version of OpenCollar are you using? 8.2.1

What behavior did you expect? 
No errors!

What behavior did you see instead? 
[00:55] Puppy Collar: Puppy Collar [script:oc_rlvextension] Script run-time error
[00:55] Puppy Collar: Stack-Heap Collision

What steps does someone need to take to reproduce the problem?
I have no idea, the error happened upon login.
Only IMs and TP blocked by the collar, though several other restrictions from other worn attachments.
If oc_rlvextension handles exceptions then my 3 Owners (One of which is me) and 11 Trusted may be the issue.

**Comment by mistressohm** [comment]
I would suspect that other scripts would crash first, with that many
Trusted UUID's loaded into memory.  That's a BIG string to pass, if it is
being passed.

The way to test this, without anyone losing access, would be to create a
group, put all the Trusted people in it, and then set Group Access on the
collar to On for that group.  That allows the collar to check one ID (the
group) rather than 11 individual UUID's.  Keep in mind that this WILL lock
you to that Group (you won't be able to change group tags) for as long as
Group access is enabled.

 If the stack heap collision issue stops, you've discovered where the
problem is.  If it doesn't stop, then you can poke around further.

**Comment by DeaEnyo** [comment]
Thank you, I won't be able to wrangle everyone into a single group and it was a one-time error that hasn't happened before or since but I will keep a closer eye on messages each time I log in.
I DO wonder if the 28 UUID limit is a bit generous if 11 is 'pushing it' but due to my permanent restrictions I suppose the collar has to 'work harder' running the exceptions for every one.
(Related but probably not worth filing a bug report: the access list cuts off before reaching the end (group and public access info) with even 11 names in list
