### ISSUE TITLE
Avatar list when using OC Remote

### ISSUE THREAD

**Issue by TESkeet** [OpenCollarTeam/OpenCollar#793]
What version of OpenCollar are you using? 
OpenCollar 8.2.1000

What behavior did you expect? 
I would expect that when trying to use the remote to connect to a collar that my name would be 0 rather than the last on the list.  This is an issue when the remote finds 20 people and only 12 get listed, of which I am not one.

What behavior did you see instead?  
I would like to see the list sorted by distance, with ME being the closest avi.

What steps does someone need to take to reproduce the problem?  
It's common to everyone if you're in a crowd of people.  It could be a simple ascending or descending list to fix this code.

**Comment by KristenMynx** [comment]
I tested this a bit to understand the issue.   The sorting by distance is already done (it's built into llSensor()).   However llSensor() does not include the avatar wearing the object from which it is called.   In order to include the wearer, the code adds the wearer to the end of the list.  

The change is simple enough, add the wearer to the beginning of the list.   The side effect is that in a crowded space, the one less person would be shown.   This is good if the majority of AO remote users want to choose themselves.   This is (potentially) bad if the majority of AO remote users do no want to choose themselves, and therefore loose one choice in a crowded area.

AO remote users feedback please.

**Comment by AlexNumberFour** [comment]
Well, I'll gladly trade one less person on the list, if I can at least select myself while in an area with a large amount of collar users. 

In such an environment, I can't even use the remote control on myself.

**Comment by TESkeet** [comment]
That was the reason I posted this.   You get left out of the list.  If you were FIRST in the list you would not be truncated off the list, ever.

**Comment by SilkieSabra** [comment]
This issue needs to be reopened at https://github.com/OpenCollarTeam/Remote/issues
