### ISSUE TITLE
If a sub is leashed, then crashes, when she relogs she gets pulled into walls if I am somewhere else. Option UNLEASH UPON LOGIN would be nice

### ISSUE THREAD

**Issue by donelson52** [OpenCollarTeam/OpenCollar#800]
What version of OpenCollar are you using?
Any version starting ten years ago

What behavior did you expect?
Sub not being pulled by leash into walls upon relog after crash

What behavior did you see instead?
Sub punished by being pulled into walls

What steps does someone need to take to reproduce the problem?
Leash a sub, have her relog, while she is gone move to another room

If a sub is leashed, then crashes, when she relogs she gets pulled into walls if I am somewhere else. Option UNLEASH UPON LOGIN would be nice

**Comment by donelson52** [comment]
I used to have a script to do this, but it no longer works.

**Comment by mistressohm** [comment]
I've had this happen to my pet a time or two.  I have to remember, when she
says "good night" I need to unleash her, or she'll get yoinked across the
room on login if I'm in the same parcel.

The ONLY time leash-state should be 'persistent' on login, is if it to a
rezzed object, not an attachment.

**Comment by AnatovaAkina** [comment]
There is already checking done on the proximity of the leash target (leasholder) and wearer, in oc_leash, in the timer() function. If the distance between the two is too large, the leash will temporarily be deactivated. However, this distance is currently set to 60 meters + the leash length. It would make sense to make this number variable, make it smaller after relog or when the leasholder disappears from the sim. Like 5m + length. And make it 60m when the leash is established again.

**Comment by cruelraremaster** [comment]
First, the scripts are unable to determine if relog was done intentionally or it's been a normal logoff-login again or caused by a crash. So any change would affect "normal" logout as well.

The I think in "strict" leash mode, the behavior should not be changed.

But then for a leashing in non-strict mode, I think it could make sense to UNLEASH UPON LOGIN but if and only if the wearer was leashed to a PERSON, not to a Anchor.

I consider that a useful change but I didn't tested the behaviour of the current version. @SilkieSabra ?

**Comment by SilkieSabra** [comment]
The leash reinstates when the wearer or leash holder relogs after a logoff or crash, and is active even if the leash holder is absent, as long as the leash holder or wearer did not unleash.

**Comment by SilkieSabra** [comment]
So yes, if you do not unleash your sub, then log off and log on in a different place in the same region, your sub will get yanked.

**Comment by SilkieSabra** [comment]
This issue therefore should be either closed or labeled as a Feature request to tweak it a little bit.

**Comment by SilkieSabra** [comment]
I think Unleash upon Login will not be a universally popular change so i lean toward leaving it as is

**Comment by Yosty7B3** [comment]
One of the suggestions was reducing the break distance on login, and increase it again when connection is established.
That does sound like a reasonable alternative.

**Comment by donelson52** [comment]
Make it an option in the leash settings. There are MANY MANY options, adding one "Unleash upon login" or "Unleash upon login after N minutes" or "Ask to re-leash after login" or "Ask to re-leash if great than N meters away" or any number of things to PREVENT MY SUBS FROM BEING DRAGGED INTO WALLS. Holy cow.

**Comment by Medea-Destiny** [comment]
We could have the sub teleport to the leash holder before engaging the move to target.

**Comment by mistressohm** [comment]
Medea's suggestion makes a lot of sense... as long as the owner is within
the same sim.  (Parcel would be harder to determine).

I've also seen this 'yank into corners' behavior on login... also
ceilings!  cos I ported to a skybox and the sub logs back in and gets
yeeted upward.

So no, not a feature, this is definitely a QoL issue that needs some
tweaking.  :)   If the collar can determine distance, then making the leash
"break" past a certain point is a good plan.  Freeze the sub in place if
there's a risk of someone wandering off, but not yank them into scenery.
Otherwise, some kind of prompt to tplure the sub, then releash on teleport,
would be recommended.
