### ISSUE TITLE
Create Remote Release

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#81]
We should put together a release of the Remote and make it available through our vendors.

**Comment by KristenMynx** [comment]
I can work on this.   Is the goal to take the old remote and update it?   Should the base version be the VD one (i'm not sure if that one is open or not), or a 3.9xx one?   Any thoughts changes on the UI style or feature set?   Or should the goal be just the basics?

**Comment by KristenMynx** [comment]
Ok... so I've looked at the repository.. .sorry about stupid questions before research.  I see there is already a folder for remote and scripts (to some degree updated).    It might be completed.   Is the status known?  Is it just testing that is required?   I have a 6.1.0 remote linkset.   Seems this is the right thing to load this into.   Thoughts, directions?   Thanks.

**Comment by KristenMynx** [comment]
Ok.. forked, did a couple updates (version stuff), pulled the scripts into the remote linkset.   Will do some testing from here.   I guess I'm good at this point.. I'll update on progress.

**Comment by nirea** [comment]
Thanks for jumping on this @KristenMynx!

Yes we just need a new linkset to house the scripts in the src/remote folder, with working buttons, etc.

**Comment by KristenMynx** [comment]
One note on the linkset created in the pull request:   The blindfold, gag and cuffs icon descriptions were coded to some "acc-" protocol which sent a link message within the remote to 7000.  For this iteration I changed those prim descriptions so they activate the collar's Apps menu instead.    Perhaps those 3 buttons don't even belong in the remote, if they require add-on accessories.

**Comment by KristenMynx** [comment]
@nirea I saw the dev release of this.  Great work simplifying it.   Since its now a single texture for all the buttons, there really is no need for several prims.  I could replace the several prims in favor of 2 prims.  One prim just sized for a "minimized square" and the other prim that pops out full for all the buttons.   Then use llDetectedTouchST() to determine where it was touched, and perform the corresponding action.  The actions would be moved from prim descriptions into the script itself.

**Comment by nirea** [comment]
I see pros and cons to that approach.

Your proposal would definitely be simpler.  There's a ton of code in the remote for reflowing the hud buttons in different ways, or swapping the positions of two buttons.  It seems like unnecessary complexity to me.  (Though having multiple prims doesn't necessitate having all those options.)  If we went your direction, we could go even further playing prim-count-golf and reduce it to one prim that just got bigger and smaller (and changed its texture scale appropriately).

There are some things I like about the current setup. I like how the minimize/maximize button tries to sit in the corner of the screen, changing its movement rules depending on which HUD attach point you're using.  It might be possible to do that in a 1-2 prim approach but I'm not sure yet.  I like that we can change the button order without having to create a new texture.  The multi-prim setup could also support having optional buttons that only show if explicitly enabled (this might be a good way to bring back the gag/cuffs/blindfold buttons for people who want them).  We could do nice little UI touches like tinting a button while it's pressed.

An intermediate solution would be to have a mesh object with multiple faces on the same side (like the current OC vendor).  We could still decouple the texture from the button arrangement that way.  If the object were covered with square faces and shaped like a 3D box, say, 1 x 3 x 6, then we could have a 3 button minimized mode, an 18 button maximized mode, and a 6 button mode in the middle.

I'd like to hear opinions from regular remote users on their UI preferences.  Do they want optional buttons?  Little/big/medium modes?  Any specific buttons that we don't have?  Though I have my own preferences around ease and flexibility of different implementations, I'd like mainstream users' opinions to carry the most weight.

**Comment by KristenMynx** [comment]
@nirea Ok..  I assumed that you had removed the button rearrangement code.  My mistake.  This makes my suggestion inapplicable.    If you decide to go with a faced-mesh approach I can help make that happen too.

**Comment by nirea** [comment]
Related question: Do we need an updater for the remote?  It does include code for interacting with an updater.

Compared to collars, updateability of the remote is much less important, since the scripts aren't typically installed into third party designs.  It's probably easier to just grab a new remote and add your subs than grab an updater and wait through an update process.

I'd want to maintain updateability if people commonly add their own rezzable objects or plugin scripts.  Not sure how common that is.

But if we do stay committed to updateability, then changing the prim setup becomes a lot more complicated.

**Comment by KristenMynx** [comment]
@nirea : Do we need an updater?
My short answer: No.  (alternative given below as well)
Longer answer.  I'll venture a guess that 90% of updates to products in SL consist of receiving a new copy of the updated product.    I'd probably venture further to say its 99.9%.

So why is the collar different?   Because its a single product that is contained within hundreds of other products, of many brands, shapes, sizes and construction.  This is the only practical way to let anyone update (to the latest version) the vast variety of collar (and collar like) devices out in the wild, even when their creators are long gone from the grid.    

With this in mind, I'd say that the AO and Remote will not be customized by many (if any) creators.   Also I'm thinking that the feature set of AO and Remote won't change much over time, making the frequency of updates fairly low.   Continuing on that thought, (almost) any added feature probably needs a button, and therefore a new button prim, therefore requiring a new link set, therefore negating any advantage that the update provided.

Another approach, which could work, would a kind of automated "transfer", instead of an update.   When a user gets a new version of a device, they use a "transfer" option from a menu..  Any animations, LMs, notecards, or objects, that don't already exist in the new device are pushed from the old one to the new one.

**Comment by KristenMynx** [comment]
Once this last pull is done it should be ready to release.  (don't forget to remove 'dev2' suffix in the code)

@nirea Initially I changed the version to 7.0, then I noticed you had 1.5 in the release notes.   So I changed everything to 1.5.  Just verifying this is correct.

**Comment by nirea** [comment]
1.5 sounds good.  Trying to keep collar and hud version numbers in sync would get awkward.

Awesome work!
