### ISSUE TITLE
Lock and Bell both show when locking.

### ISSUE THREAD

**Issue by pcbeeswing** [OpenCollarTeam/OpenCollar#810]
What version of OpenCollar are you using? 8.2

What behavior did you expect? Locking and unlocking collar should not reveal the bell when it's hidden.

What behavior did you see instead? Any time you lock or unlock the collar the hidden bell becomes visible.

What steps does someone need to take to reproduce the problem? Build a collar with a bell and a lock, and hide them then lock or unlock the collar.

**Comment by SilkieSabra** [comment]
@pcbeeswing , what collar model do you have? Sometimes this can happen due to building issues in the collar model.  Can you duplicate on a stock OpenCollar from the vendor

**Comment by pcbeeswing** [comment]
I've been sick with Covid for the past few weeks, and had to have a friend test this for me. She tried with the collar from OC, and had to add a bell and padlock, but it recreated the same issue I'm having.

**Comment by tenshilove** [comment]
Same issue here: lock and bell appear at the same time when locking. The lock prim has Lock as description; the bell prim has as description bell~noshiny.

**Comment by Pingout** [comment]
This appears to be an error in the Build your collar guide.
The correct description for the bell should be: Bell ~nohide
So you might ask: how does that work, wouldn't the bell be visible all the time?
It turns out that the ~nohide flag is a toggle which will remove the bell from any Show/Hide command from the collar
Bell Show/Hide is controlled by the oc_bell script
https://opencollar.cc/docs/How-to-Build-Your-OpenCollar has been corrected, thank you for the bug report!

**Comment by pcbeeswing** [comment]
> This appears to be an error in the Build your collar guide. The correct description for the bell should be: Bell ~nohide So you might ask: how does that work, wouldn't the bell be visible all the time? It turns out that the ~nohide flag is a toggle which will remove the bell from any Show/Hide command from the collar Bell Show/Hide is controlled by the oc_bell script https://opencollar.cc/docs/How-to-Build-Your-OpenCollar has been corrected, thank you for the bug report!

Thank you.
