### ISSUE TITLE
Trap Restrictions Unwanted Behavior

### ISSUE THREAD

**Issue by Omnia2021** [OpenCollarTeam/OpenCollar#842]
What version of OpenCollar are you using? 8.2.2 Beta

What behavior did you expect? No change in ability to detach collar and no ability to detach collar

What behavior did you see instead? After releasing from trap and clearing restrictions @detach was also cleared allowing for removal of a locked collar

What steps does someone need to take to reproduce the problem? Sit on a trap be released then clear restrictions and detach locked collar

**Comment by Medea-Destiny** [comment]
So... RLVsys will apply a detach if there are external sources, such as a relay. When the relay is released, the external sources become empty and the detach is removed. As the collar's lock status is not handled in rlvsys, this is a problem. I have a fixed version of rlvsys in world that re-establishes the lock if the collar was locked (which also required making rlvsys respond to an unlock as well as a lock, oops.)

HOWEVER, while I was looking through this I have noticed that we have some other issues with the relay in its current form which I want to spend a bit of time investigating, and there's a bug with the trust wearer and trust trusted buttons which don't work -- not new to this version I see, but presumably nobody noticed because the menu doesn't actually tell people what those buttons are supposed to do.

I can provide the updated RLVsys script for people to test in-world for the specific issue mentioned here which seems to be fixed now, but I'd like to do a bit of a deep dive into the relay script before it gets released into the wild.

**Comment by SilkieSabra** [comment]
What is the time frame on that, should we wait 8.2.2 release for it?

**Comment by Omnia2021** [comment]
You can send that my way if you like Medea, thanks.
