### ISSUE TITLE
Put new undress functionality into core collar

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#85]
Over at https://github.com/OpenCollarTeam/OpenCollar/issues/83 I made a change to the oc_undress script that makes the "Rem. Attach." menu a lot more user friendly.  It's now a list of things the sub is wearing instead of a list of attach points.  See https://gyazo.com/ed65f122abaf674fc09c058e9621a3e1 for how it looks now.

With this usability improvement, I think this feature would be really nice in the collar core, instead of buried deep in the menu of an optional plugin.  I could add it pretty easily to the core RLV script, or we could have a new script with just this in it to add an Undress button to the RLV menu.  

I propose adding this feature to the default collar, but not adding all the other stuff from oc_undress.  Note that this would be useful for removing attachments like mesh clothing, but couldn't remove clothing layers or mesh body appliers.

I want others' opinions:

1. Would you like this feature in the core collar?
2. Do you think we should build it into the core RLV script or have it separate?

**Comment by nirea** [comment]
Tagging @SilkieSabra, @Athaliah, @SatomiAhn specifically for opinions.  And anyone else interested of course!

**Comment by Psych0babble** [comment]
This looks a lot more inline with how the RLV folders look now (except it only shows folder names).  I like it!  I've been using RLV folders mostly for undressing (except where you need a specific toy in addition to a normal outfit), this definitely simplifies the undressing without having to go through lots of folders.

The pros:  This would make it easy for those who don't understand the foldering system to remove things immediate (especially if you don't list things within nostrip folders, and put Undress as a top level command to find it easy).  It would also be great if an attachment could send the undress command to the collar through clicking it (like the obvious halo Satomi Ahn uses).

The cons: This would make 3 ways to work with attachments: outfits, folders and undress, which might be a bit confusing as to which to use.  

Keeping it as a plug in is one option.  But if we integrate it instead, grouping it with outfits and folders seems logical to me (whether in the RLV script or a dress script), especially if this keeps them grouped in the menu in a way that they make sense and its easy to know what to choose.  

Another alternative (which would probably be another issue # all together) might be to rethink the way we work with folders that combines and simplifies the 3 different functions somehow... but that would take lots of brain storming.  (I'm looking at some other wardrobe systems to see how they work with RLV folders to come up with ideas.)

/me's favorite part of the collar is the dressing system, so he had a lot to say. *grins*

**Comment by SilkieSabra** [comment]
i think this returns a whole lot of functionality to the strip menu, that really hasn't been there for years, ever since attachments became part of every outfit. It doesn't necessarily make smartstrip obsolete but it gives more flexibility to undress for wearers who don't want to mess with the fussy directories necessary to use smartstrip.

**Comment by Athaliah** [comment]
1.  no, 2, add it to the RLV script.    Am open on this but my thoughts:
My first question is that will this only work for RLV enabled people or will this feature work for all those enabled and not enabled?  Will we need to have a collar wearer setting to allow others to dress them.  At that point, should it really be part of the core collar design or as a drop in plugin script as the whole point is to have a very lightweight collar script.   I think it might need to be its own script if its only for RLV users as its a pretty high level knowledge item, as the collar wearer would need to know how to manage the folder system, the attachments and how everything works together.

**Comment by nirea** [comment]
No @Athaliah, this change makes it so you can undress someone without any special folder setup and without knowing beforehand which things are attached to which points.

When I say "core collar" I just mean included in the default set of scripts.  I agree that one of the default RLV scripts would be the right place for it, and the button should show under the RLV menu.

**Comment by SatomiAhn** [comment]
In a nutshell, I would say go for it. We need this plugin. I also believe that many features should be added, but I see no reason not to publish it as it is now. More can be added to it later.

My (maybe unorganized) thoughts:

- yes, we want this in the rlv script. We had un/dress, and this is the new un/dress (provides roughly the same features, adapted to current technical background).
- current rlv un/dressing, based on folders, requires too much set up for it to be really popular or even usable for most people. Thus current situation does not provide a feature set on par with what we used to have (in terms of ease of use).
- that said, folders are still useful as they make possible finer control. Probably we want both systems, but as @Psych0babble remarked, too many menu entries may be confusing. It would be nice if we could "integrate" both systems into a single plugin (I will try to make a proposal, but not now).
- (feature) A typical avatar wears lots of attachments. It would be nice to have some way to filter (by keyword) or categorize (head/upper body/lower body... con: rigged mesh can be attached anywhere).
- (feature) We could also add to this menu the result of a @getoutfit RLV query, so that clothing layers could also be removed from this menu. Con: it makes the plugin more complicated (scriptwise) as it needs to be, since @getoutfit and llGetAttachedList() are two totally different mechanisms. And by using RLV queries, we would lose the immediateness of the pure LSL function call. We had this talk in group chat, I mention it for the sake of completeness, but I am not strongly in favor of such an addition (considering that people who would need the new un/dress typically would not care about clothing layers... maybe except shoe bases)
- (feature) For advanced users, it would be nice, when the user clicks the button, instead of stripping the attachment, it would pop up a (contextual) submenu, proposing a set of actions such as: 
  * strip attachment
  * lock attachment
  * lock the folders containing a link to this attachment
  * open the (first) folder containing a link to this attachment (sends a request to oc_folders)
  * "open" the spot where it's attached to (opens a subsubmenu with actions related to this spot: lock attach, lock detach, strip all attachments worn here, strip or lock all folders containing an attachment for this spot, ... )
  * ... 
- (feature) Provide a way to mark folders such that worn attachments having a link in that folder are hidden as such in this menu, but instead appear under a single entry having the folder name (thus allowing more explicit/shorter names, and allowing stripping the whole folder instead of just one attachment).

**Comment by xEmpiricalx** [comment]
I was wondering if we can clean the buttons too so that it only shows the numbers to the corresponding list. Rather then : 
Example :
current  [ 00 tram  F728 ]  to something like [ 00 ]

**Comment by nirea** [comment]
Showing just button numbers is possible, though will take a little more
scripting.  The current numbering is being done automatically by the Dialog
plugin.

**Comment by PeeBeeMcMillan** [comment]
Greetz, out there!

I'll chip in, because this has been  on my "wishful thinking" list for years. Hehe.

Everything, that anyone said so far is valid and true. I would apply the KISS rule, though: Keep It Smart & Simple. Personally, as a power user and designer, I don't think the folder/outfits system needs a -full- overhaul, but Nirea's added undressing proposal is a BIG improvement.

Undress by attachment point is utterly useless nowadays, with the multiple attachments per point and mesh attachments in general. Theoretically, a shoe could be attached to the head (memories, anyone? :P) and there is no way of knowing that as a menu operator.

RLV outfits can only be detached as whole and we have no easy way to get a list of single items within an outfit. So it's only possible to take one part of an outfit off, if the wearer has set up the same item link in a separate RLV folder.

Providing a plain and simple way to take off single, currently worn items by list, is perfection in terms of every day usability and I'm very much looking forward to this implementation!

**Comment by Athaliah** [comment]
Am enjoying the discussion on this and with the new information, I'm changing my thoughts on this, that it should be added to the core product as the overhaul as long as we keep it simple and not overload it with so many features that it becomes a mess.

**Comment by SatomiAhn** [comment]
We could also choose to modify the behavior of the Dialog plugin (quite easy). Then this would be the default behavior for all dialogs, but why not? In this case, I suppose this change should be discussed in a separate issue.

**Comment by nirea** [comment]
PeeBee's comment is reminding me though that there's a subtle issue under
the hood.  The script is still using "@detach:<attach point>" to detach the
item, which means that if multiple thing are attached at one place they
will all come off.

BUT it looks like RLV now supports a newer "@remattach:<uuid>" syntax that
would let us detach JUST the thing we're interested in.  See
http://wiki.secondlife.com/wiki/LSL_Protocol/RestrainedLoveAPI#Clothing_and_Attachments

So, I'm going to make that change, then move this into the core (probably
in oc_rlvsuite).

**Comment by silentwar-resident** [comment]
You speaking of similar to legacy undress add on?

Nathan
Sysop of Internetking BBS
Internetking@bbs.internetking.us
 
Sent from my T-Mobile 4G LTE Tablet


-------- Original message --------From: Athaliah <notifications@github.com> Date: 1/4/18  10:09 AM  (GMT-08:00) To: OpenCollarTeam/OpenCollar <OpenCollar@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [OpenCollarTeam/OpenCollar] Put new undress functionality into core collar (#85) 
Am enjoying the discussion on this and with the new information, I'm changing my thoughts on this, that it should be added to the core product as the overhaul as long as we keep it simple and not overload it with so many features that it becomes a mess.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenCollarTeam/OpenCollar","title":"OpenCollarTeam/OpenCollar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenCollarTeam/OpenCollar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Athaliah in #85: Am enjoying the discussion on this and with the new information, I'm changing my thoughts on this, that it should be added to the core product as the overhaul as long as we keep it simple and not overload it with so many features that it becomes a mess.  "}],"action":{"name":"View Issue","url":"https://github.com/OpenCollarTeam/OpenCollar/issues/85#issuecomment-355355900"}}}

**Comment by nirea** [comment]
645c80963473ac06c8bb05816d4921f1385d08b5 makes the detach feature uuid-based instead of attach point-based, and builds it into oc_rlvsuite (though it's also still in oc_undress, and maybe we should just not even include that in spares anymore).

It doesn't try to protect bodyparts from being detached.  I can't think of a way to do it cleanly, and am not feeling super motivated to do it uncleanly.  If someone has a good idea, please make a ticket for that.

The new feature has been sent in a dev release to the R&D group.

**Comment by Psych0babble** [comment]
I made a change to the DetachMenu function (in oc_rlvsuite) my own collar with the following code.  This seems to get rid of all the items I don't want to see in my specific case (since maitreya puts the word "body" in its hands and feet too).  Just a thought in case anyone is interested.

    for (n = 0; n < iStop; n++) {
        key k = llList2Key(attachmentKeys, n);

        //Added 7 lines:
        list lDetachFilters = ["nails", "body", "piercing", "head", "ears", "eyes"];
        integer keep = 1;
        integer i;
        for (i = 0; i < llGetListLength(lDetachFilters); i++) {
            string sName = llToUpper(llKey2Name(k));
            string sFilter = llToUpper(llList2String(lDetachFilters, i));
            if (~llSubStringIndex(sName, sFilter)) {  keep = 0; }
        }

        //Added " && keep":
        if (k != llGetKey() && keep) {
            g_lAttachments += [llKey2Name(k), k];
        }

**Comment by Psych0babble** [comment]
Since this thread is closed I opened the proposal above as issue #89

**Comment by leonardmaynard702** [comment]
**https://stitch82.blogspot.com**

**https://stitch82.blogspot.com**
