### ISSUE TITLE
Capture has a problem

### ISSUE THREAD

**Issue by 1Acadia** [OpenCollarTeam/OpenCollar#903]
What version of OpenCollar are you using? 8.2.3000

What behavior did you expect? After someone captures me and I am released by the captor, or timeout after they leave, I expect to have full functionality returned to me.

What behavior did you see instead? I keep getting this message when I try to look at the Access list after someone uses the capture and I have long since been released.  This is the 3rd time it has happened: [19:08] Heavy_Collar_Cadi: Access Denied to the access settings while capture is active!  The only way I have found to fix it, is to reset the collar scripts.

What steps does someone need to take to reproduce the problem? There are too many variables after I am captured. i.e cuffs, rlv devices, to know what causes it. But auth=tempowner is not getting cleared at times.

**Comment by SilkieSabra** [comment]
This needs testing ! Readers please see if you can duplicate this.

**Comment by Pingout** [comment]
I tested the Capture App with an alt, and was able to duplicate the problem. 
When I capture the alt and leave the sim, the 10 minute timer starts, but at the end of ten minutes the alt can not get the access menu.  When I come back later, like another 10 minutes, and get the Apps / Capture menu, it gives me the option to end the capture still. The problem is at the end of the timer. When the timer ends, the capture does not clear out on it's own.
When I end the capture using the menu, the alt can get the access menu

**Comment by meganlawalert** [comment]
We have experienced numerous problems with capture automatic release not releasing and actually leaving the capture stuck.  On a welded collar, this results in needing to login with RLV disabled, reset the collar scripts, then login with RLV and rebuild the collar state.  The OWNER of the collar MUST be able to reset the capture, perhaps by toggling it off then back on.
