### ISSUE TITLE
Template for plugins

### ISSUE THREAD

**Issue by masterofsorts** [OpenCollarTeam/OpenCollar#91]
There used to be a developer template for plugins, I think this was deleted around the time the paid for apps were introduced

Could someone recreate it?

**Comment by SilkieSabra** [comment]
This is related to issue # 71 opened by me three weeks ago, we need a plugin template and an agreement for plugins keyed to OpenCollar

**Comment by KristenMynx** [comment]
If this is a task that should be done sooner rather than later, I can take this on.   I've developed a few plugins for OC for my things, based on a centuries old template.   They'd needed a bit of modification for 6, but still work fine for 7.

I wouldn't mind turning it back into a generic sample along with some wiki docs.

I'd want to include documentation the CMD_ZERO/AUTH cycle so a less than advanced scripter can get a handle on what is required.    I can also include whatever information/notices that #73 refers to.

**Comment by zontreck** [comment]
This has been resolved.
