### ISSUE TITLE
Add llGetAttachedList-based menu for locking attachments

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#92]
This would be similar to how we're doing Detach now, but for locking instead.  It's more complicated under the hood, since locking by UUID wouldn't make sense (UUIDs change on relog).  But we could still select things by an llGetAttachedList menu, then figure out the attach point of the selected item and lock that.  @SatomiAhn has some ideas on how folder setup could add more features for people who are willing to set those up.

**Comment by SatomiAhn** [comment]
Concerning folders, what I propose is to make it easy, for people who put their worn attachments in #RLV folders, to lock the folder containing the selected attachment.

Steps:
1. get the object UUID through llGetAttachedList
2. get the containing folder(s) using @getpathnew:UUID=chan
3. if the answer is a single folder, issue @detachthis:path=n

The details of the UI must be discussed though. Should this be the default behavior, with fall back to locking by attach point? Or just a separate button that appears only if folders are set? (probably a better option, since this means less surprise as to to the actual behavior)

Also, maybe instead of going to step 3, the folder menu from oc_folder plugin should be opened for this path.

**Comment by ExecuterMagic** [comment]
The basic idea sounds good , but ( not a scripter myself ) it brings up some questions for me :

@nirea : if it finds out the atachment point , and locks that , as far as i know many mesh items by default simply attach to the right hand , would that not lock everything else beeing at that slot as well ?

@satomi : Would that mean that each atachment has to be in a seperate folder for that to work ? could imagine that to be quite a lot of setting up , and clutter the folder menu , or not ?

**Comment by SatomiAhn** [comment]
@ExecuterMagic : 

- answering for @nirea: definitely, but unfortunately RLV does not a provide to detach an object by UUID. Detaching by spot name is the best that can be done currently (unless there is a special set up with folders).
- answering for myself: what I propose is just some additional, optional, feature for people who want to set up their folders. I am aware this is no panacea. As for clutter, I believe it may be worth it, if it gives access to the whole folder menu (with all related commands).

**Comment by ExecuterMagic** [comment]
@ satomi
Yes , a good feature for sure , was not criticising , only asking , and sure worth it ,  will need some good tutorial imho tho , assume there is no possibility to reach out for marine about some future improovements for that in RLV ?

**Comment by SilkieSabra** [comment]
Again, a good but dated discussion.
