### ISSUE TITLE
request: [prefix] core lock/unlock (also a minor bug)

### ISSUE THREAD

**Issue by eksynn** [OpenCollarTeam/OpenCollar#992]
What version of OpenCollar are you using?
8.2.3
What behavior did you expect?
not applicable
What behavior did you see instead?
hoping for a command to be added to lock and unlock the outfits/core folder.
(also a bug I found is that when opening the menu, it opens twice)
What steps does someone need to take to reproduce the problem?
[prefix] core lock
[prefix] core unlock

**Comment by SilkieSabra** [comment]
I'm not sure about the menu opening twice, I'd have to see that duplicated.  Are you finding that you cannot unlock core, if you are not the owner?  Or are you just requesting the chat command be added? If the former that is already fixed in the next version branch, https://github.com/OpenCollarTeam/OpenCollar/blob/8.3_Features-branch/src/Apps/oc_outfits.lsl .
